require_relative "shared/report_templates.seed.rb"
require_relative "shared/molecules.seed.rb"
require_relative "shared/text_templates.seed.rb"
require_relative "shared/rdkit.seed.rb"
require_relative "shared/ontologies.seed.rb"
