# inherit_from: .rubocop_todo.yml

inherit_gem:
  gitlab-styles:
    - rubocop-metrics.yml
    - rubocop-rspec.yml

require:
  - rubocop-rspec
  # TODO: install rubocop-rails
  # - rubocop-rails
  - rubocop-performance
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6.6
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  CacheRootDirectory: tmp
Style/Documentation:
  Enabled: false
# Rails:
#   Enabled: true
#   Exclude:
#     - 'Guardfile'
#     - 'bin/**/*'
#     - 'config/*'
#     - 'config/**/*'
#     - 'tmp/**/*'
#     - 'Rakefile'
RSpec:
  Include:
    - 'spec/**/*_spec.rb'
