services:
  db:
    image: ptrxyz/chemotion:db-2.0.1
    restart: unless-stopped
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - chemotion_db:/var/lib/postgresql/data/
    networks:
      - chemotion

  eln:
    build:
      context: .
      dockerfile: Dockerfile.p2d
      args:
        - BRANCH=$BUILD_BRANCH
    restart: unless-stopped
    environment:
      - CONFIG_ROLE=combine
      - SECRET_KEY_BASE=pleasechangeme
      - RUBYOPT=-W0
    depends_on:
      - db
    ports:
      - 4000
    networks:
      - chemotion

volumes:
  chemotion_db:
    name: chemotion_db

networks:
  chemotion:
