FROM complat/chemotion_eln_runner:v1.7.0-3
ARG BRANCH=main
RUN apt-get install -y --no-install-recommends --autoremove --fix-missing \
  build-essential\
  openssh-server\
  libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

WORKDIR "/chemotion/app"

# avoid caching if newer commits are present
ADD "https://api.github.com/repos/ComPlat/chemotion_ELN/commits/${BRANCH}?per_page=1" latest_commit.json

RUN curl -LJO https://raw.githubusercontent.com/ComPlat/chemotion_ELN/${BRANCH}/Gemfile 
RUN curl -LJO https://raw.githubusercontent.com/ComPlat/chemotion_ELN/${BRANCH}/Gemfile.lock
RUN curl -LJO https://raw.githubusercontent.com/ComPlat/chemotion_ELN/${BRANCH}/package.json
RUN curl -LJO https://raw.githubusercontent.com/ComPlat/chemotion_ELN/${BRANCH}/yarn.lock

# COPY Gemfile .
# COPY Gemfile.lock .
# COPY package.json .
# COPY yarn.lock .

RUN bundle config set without ''
RUN bundle install
RUN yarn install --production=false

