FROM ubuntu:18.04

ARG DEBIAN_FRONTEND=noninteractive

RUN set -xe  && apt-get update -yqqq --fix-missing && apt-get upgrade -y
RUN apt-get install -yqq bash ca-certificates wget apt-transport-https git \
      imagemagick libmagic-dev libmagickcore-dev libmagickwand-dev curl gnupg2 \
      build-essential nodejs sudo postgresql-client libappindicator1 swig \
      fonts-liberation xvfb gconf-service libasound2 libgconf-2-4 cmake \
      libnspr4 libnss3 libpango1.0-0 libxss1 xdg-utils tzdata libpq-dev \
      gtk2-engines-pixbuf xfonts-cyrillic xfonts-100dpi xfonts-75dpi \
      xfonts-base xfonts-scalable unzip openssh-client \
      python-dev libsqlite3-dev libboost-all-dev p7zip-full
RUN  wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list \
    && apt-get update -yqqq && apt-get -y install google-chrome-stable \
    && CHROMEDRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE` \
    && mkdir -p /opt/chromedriver-$CHROMEDRIVER_VERSION \
    && curl -sS -o /tmp/chromedriver_linux64.zip http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip \
    && unzip -qq /tmp/chromedriver_linux64.zip -d /opt/chromedriver-$CHROMEDRIVER_VERSION \
    && rm /tmp/chromedriver_linux64.zip \
    && chmod +x /opt/chromedriver-$CHROMEDRIVER_VERSION/chromedriver \
    && ln -fs /opt/chromedriver-$CHROMEDRIVER_VERSION/chromedriver /usr/local/bin/chromedriver
RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/*
RUN useradd -ms /bin/bash gitlab-runner \
    && echo "gitlab-runner ALL=NOPASSWD: ALL" >> /etc/sudoers

USER gitlab-runner
WORKDIR /home/gitlab-runner

RUN gpg2 --keyserver hkp://ipv4.pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB \
    && \curl -sSL https://get.rvm.io | bash -s stable \
    && echo "source ~/.rvm/scripts/rvm" >> ~/.bashrc \
    && echo 'if [ -f ~/.bashrc ]; then \n  source ~/.bashrc\nfi' > ~/.bash_profile

RUN cat ~/.bash_profile

RUN mkdir -p shared/bundle/ruby
RUN mkdir -p shared/node_modules
RUN ln -s shared/node_modules node_modules
RUN echo $(ls -1 .)

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash

COPY Gemfile /home/gitlab-runner/
COPY Gemfile.lock /home/gitlab-runner/
COPY package.json /home/gitlab-runner/
COPY package-lock.json /home/gitlab-runner/
RUN echo $(ls -1 .)

RUN /bin/bash -l -c "source ~/.nvm/nvm.sh && nvm install 10.15.3 && npm install -g npm@6.11.3 && npm install"
RUN echo $(ls -1 shared/node_modules)
RUN /bin/bash -l -c "source ~/.rvm/scripts/rvm && rvm install 2.5.6 && gem install bundler -v 1.17.3 && bundle install --path shared/bundle"
# RUN /bin/bash -l -c "source ~/.rvm/scripts/rvm && chromedriver-update"
