# This dockerfile is used by docker-compose.dev.yml
# It builds a container with all the necessary gems to run chemotion ELN
# WARNING: Building this container initially takes a lot of time, due to gem compiling, so grab a coffee
# and write some documentation meanwhile ;)

FROM --platform=linux/amd64 ubuntu:jammy

ARG DEBIAN_FRONTEND=noninteractive
ARG FULL_BUILD=false
ARG BRANCH=main

RUN set -xe  && apt-get update -yqqq --fix-missing && apt-get upgrade -y
RUN apt update && apt-get install -yqq --fix-missing bash ca-certificates wget apt-transport-https git gpg\
      imagemagick libmagic-dev libmagickcore-dev libmagickwand-dev curl gnupg2 \
      build-essential sudo postgresql-client libappindicator1 swig \
      gconf-service libasound2 libgconf-2-4 cmake \
      libnspr4 libnss3 libpango1.0-0 libxss1 xdg-utils tzdata libpq-dev \
      gtk2-engines-pixbuf \
      libssl-dev libreadline-dev\
      unzip openssh-client \
      libsqlite3-dev libboost-all-dev p7zip-full \
      xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable \
      fonts-crosextra-caladea fonts-crosextra-carlito \
      fonts-dejavu fonts-dejavu-core fonts-dejavu-extra fonts-liberation2 fonts-liberation \
      fonts-linuxlibertine fonts-noto-core fonts-noto-extra fonts-noto-ui-core \
      fonts-opensymbol fonts-sil-gentium fonts-sil-gentium-basic inkscape \
      libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libxtst6 xauth xvfb nano jq
RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/*
RUN useradd -ms /bin/bash chemotion-dev \
    && echo "chemotion-dev ALL=NOPASSWD: ALL" >> /etc/sudoers

USER chemotion-dev
WORKDIR /home/chemotion-dev

# Create node modules folder OUTSIDE of application directory
RUN mkdir /home/chemotion-dev/node_modules

SHELL ["/bin/bash", "-c"]

# Even if asdf and the related tools are only installed by running run-ruby-dev.sh, we set the PATH variables here, so when we enter the container via docker exec, we have the path set correctly
ENV ASDF_DIR=/home/chemotion-dev/.asdf
ENV PATH=/home/chemotion-dev/.asdf/shims:/home/chemotion-dev/.asdf/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV NODE_PATH=/home/chemotion-dev/node_modules

RUN git clone --single-branch --branch=$BRANCH https://github.com/complat/chemotion_ELN app

# Install asdf if FULL_BUILD is set to true
WORKDIR /home/chemotion-dev/app
RUN if [ "$FULL_BUILD" = "true" ]; then \
      ./prepare-asdf.sh; \
    fi

# Install ruby and nodejs if FULL_BUILD is set to true
RUN if [ "$FULL_BUILD" = "true" ]; then \
      ./prepare-rubygems.sh; \
    fi

# Install nodejs packages if FULL_BUILD is set to true
RUN if [ "$FULL_BUILD" = "true" ]; then \
      echo -e "--modules-folder ${NODE_PATH}\n" > /home/chemotion-dev/app/.yarnrc; \
      ./prepare-nodejs.sh; \
      ./prepare-nodejspkg.sh; \
    fi

WORKDIR /home/chemotion-dev
RUN rm -rf /home/chemotion-dev/app
