FROM ptrxyz/chemotion:eln-2.0.1
ARG BRANCH=main
ARG REMOTE=https://github.com/ComPlat/chemotion_ELN.git

RUN apt-get update && apt-get upgrade -y --no-install-recommends
RUN apt-get install -y --no-install-recommends --autoremove --fix-missing \
  build-essential\
  openssh-server\
  libmagickwand-dev \
  libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev  libnss3 libxss1  libxtst6 xauth xvfb \
  openssl libtool libssl-dev  libyaml-dev \
  swig \
  jq

WORKDIR "/chemotion/app"

RUN rm -rf public/ uploads/
RUN rm -rf tmp/cache
ADD ${REMOTE}#${BRANCH} /chemotion/app

RUN rm ${ASDF_DIR}/asdf
ENV PATH="${ASDF_DIR}/bin:${PATH}"
RUN ./prepare-asdf.sh
RUN ./prepare-nodejs.sh
ENV ASDF_NODEJS_VERSION=''
ENV ASDF_RUBY_VERSION=''
RUN asdf current && sleep 5s
RUN ./prepare-nodejspkg.sh
RUN ./prepare-rubygems.sh






