services:
  db:
    image: ptrxyz/chemotion:db-2.1.1
    restart: unless-stopped
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - chemotion

  app:
    build:
      context: .
      dockerfile: Dockerfile.p2d
      args:
        - BUILDKIT_CONTEXT_KEEP_GIT_DIR=1
    restart: unless-stopped
    environment:
      - CONFIG_ROLE=combine
      - SECRET_KEY_BASE=pleasechangeme
      - RUBYOPT=-W0
    deploy:
      resources:
        limits:
          cpus: "2.0"
    depends_on:
      - db
    ports:
      - 4000
    networks:
      - chemotion
    env_file:
      - path: .env # see https://github.com/Dokploy/dokploy/issues/385 for more details
    volumes:
      - ../files/pullin:/shared

  configure:
    image: ptrxyz/chemotion:eln-2.1.1 # same as the base image in Dockerfile.p2d for efficiency
    profiles:
      - configure
    restart: no
    volumes:
      - ../files/pullin:/shared
    healthcheck:
      disable: true
    tty: true # Equivalent to `docker run -t`
    stdin_open: true # Equivalent to `docker run -i`
    command: ["bash"]

networks:
  chemotion:
