services:
  db:
    image: ptrxyz/chemotion:db-2.0.1
    restart: unless-stopped
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - chemotion

  app:
    build:
      context: .
      dockerfile: Dockerfile.p2d
      args:
        - BUILDKIT_CONTEXT_KEEP_GIT_DIR=1
    restart: unless-stopped
    environment:
      - CONFIG_ROLE=combine
      - SECRET_KEY_BASE=pleasechangeme
      - RUBYOPT=-W0
    depends_on:
      - db
    ports:
      - 4000
    networks:
      - chemotion
    env_file:
      - path: .env # see https://github.com/Dokploy/dokploy/issues/385 for more details
    volumes:
      - ../files/pullin:/shared
  indigo_service:
    hostname: indigo_service
    image: ${IMG_INDIGO:-epmlsop/indigo-service:latest}
    environment:
      - PYTHONPATH=${INDIGO_SERVICE_PYTHONPATH:-/srv/indigo-python}
      - INDIGO_UWSGI_RUN_PARAMETERS=--plugin python3 --py-autoreload=1
      - PYTHONDONTWRITEBYTECODE=1
    networks:
      - chemotion
    command: supervisord -n

networks:
  chemotion: