FROM ptrxyz/chemotion:eln-2.0.1

ARG BRANCH=main
ARG REMOTE=https://github.com/ComPlat/chemotion_ELN.git

SHELL ["/bin/bash", "-e", "-o", "pipefail", "-c", "--"]

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,id=apt-cache \
    --mount=type=cache,target=/var/lib/apt,sharing=locked,id=apt-lib \
    apt-get update -y && \
    apt-get install -y --no-install-recommends --autoremove --fix-missing \
        git ca-certificates curl unzip nano \
        build-essential \
        zlib1g-dev libreadline-dev patchelf \
        cmake libpq-dev swig libmagickcore-dev \
        postgresql-client inkscape imagemagick librsvg2-bin locales ghostscript \
        vim iproute2 sudo make jq

WORKDIR "/chemotion/app"

RUN git remote add origin ${REMOTE} && \
    git fetch && \
    git switch ${BRANCH}

RUN rm ${ASDF_DIR}/asdf
ENV PATH="${ASDF_DIR}/bin:${PATH}"
RUN ./prepare-asdf.sh

# Ruby gems
RUN --mount=type=cache,target=/asdf/cache,sharing=locked \
    MAKEFLAGS="-j$(nproc)" && export MAKEFLAGS && \
    bundle install --jobs="$(nproc)" --retry=3 && \
    bundle clean --force

ENV ASDF_NODEJS_VERSION=''
ENV ASDF_RUBY_VERSION=''
RUN ./prepare-nodejs.sh
RUN asdf current && sleep 5s

RUN --mount=type=cache,target=/asdf/cache,sharing=locked \
    echo -e "--modules-folder ${NODE_PATH}\n--ignore-engines" > /chemotion/app/.yarnrc && \
    MAKEFLAGS="-j$(nproc)" && export MAKEFLAGS && \
    npm install -g yarn && \
    yarn install --modules-folder ${NODE_PATH} --ignore-engines --ignore-scripts 2>&1 | grep -v ^warning

RUN bash package_postinstall.sh

ADD https://raw.githubusercontent.com/harivyasi/push2deploy/refs/heads/main/payload/run.sh /embed/run.sh
RUN chmod +x /embed/run.sh


