Bundler.load.current_dependencies.select{  |dep|  dep.groups.include?(:plugins)}.map(&:name).include?("scifinding") && Scifinding.configure do |config|
  config.client_id  = ENV['SF_CLIENT_ID']
  config.client_key = ENV['SF_CLIENT_KEY']
  config.site = ENV['SF_SITE']
  config.passphrase =  ENV['SF_PASS_PHRASE']
  config.token_path = ENV['SF_TOKEN_PATH']
  config.ping_url = ENV['SF_PING_URL']
  config.pat_inf_path = ENV['SF_PAT_INF_PATH']
  config.doi_inf_path = ENV['SF_DOI_INF_PATH']
  config.cas_rn_path = ENV['SF_CAS_RN_PATH']
  config.lk_pat_path = ENV['SF_LK_PAT_PATH']
  config.lk_doi_path = ENV['SF_LK_DOI_PATH']
  config.lk_cas_path = ENV['SF_LK_CAS_PATH']
  config.ans_sub_path = ENV['SF_ANS_SUB_PATH']
  config.ans_rea_path = ENV['SF_ANS_REA_PATH']
end
