# frozen_string_literal: true

require 'English'

module Cdx
  module Parser
    # Header port from chemdrawcdx.h
    module Header
      CDX_HEADER_STRING_LEN = 8
      CDX_HEADER_STRING = 'VjCD0100'
      CDX_SIGNATURE = 'VjCD'
      CDX_HEADER_LENGTH = 28
      CDXML_HEADER_STRING = '<?xml version ="1.0" encoding ="UTF-8" ?>' +
                            $RS + '<!DOCTYPE CDXML SYSTEM ' \
                            '"http:#www.cambridgesoft.com/xml/cdxml.dtd" >' +
                            $RS
      CDX_TAG_OBJECT = 0x8000
      CDX_TAG_USER_DEFINED = 0x4000

      # GENERAL PROPERTIES.
      CDX_PROP_ENDOBJECT = 0x0000 # 0x0000 MARKS END OF OBJECT.
      CDX_PROP_CREATIONUSERNAME = 0x0001 # 0x0001 THE NAME OF THE CREATOR (PROGRAM USER'S NAME) OF THE DOCUMENT. (CDXSTRING)
      CDX_PROP_CREATIONDATE = 0x0002 # 0x0002 THE TIME OF OBJECT CREATION. (CDXDATE)
      CDX_PROP_CREATIONPROGRAM = 0x0003 # 0x0003 THE NAME OF THE PROGRAM INCLUDING VERSION AND PLATFORM THAT CREATED THE ASSOCIATED CDX OBJECT. CHEMDRAW 4.0 USES CHEMDRAW 4.0 AS THE VALUE OF CREATIONPROGRAM. (CDXSTRING)
      CDX_PROP_MODIFICATIONUSERNAME = 0x0004 # 0x0004 THE NAME OF THE LAST MODIFIER (PROGRAM USER'S NAME) OF THE DOCUMENT. (CDXSTRING)
      CDX_PROP_MODIFICATIONDATE = 0x0005 # 0x0005 TIME OF THE LAST MODIFICATION. (CDXDATE)
      CDX_PROP_MODIFICATIONPROGRAM = 0x0006 # 0x0006 THE NAME OF THE PROGRAM INCLUDING VERSION AND PLATFORM OF THE LAST PROGRAM TO PERFORM A MODIFICATION. CHEMDRAW 4.0 USES CHEMDRAW 4.0 AS THE VALUE OF CREATIONPROGRAM. (CDXSTRING)
      CDX_PROP_UNUSED1 = 0x0007 # 0x0007 TABLE OF CONTENTS. (OBSOLETE)
      CDX_PROP_NAME = 0x0008 # 0x0008 NAME OF AN OBJECT. (CDXSTRING)
      CDX_PROP_COMMENT = 0x0009 # 0x0009 AN ARBITRARY STRING INTENDED TO BE MEANINGFUL TO A USER. (CDXSTRING)
      CDX_PROP_ZORDER = 0x000A # 0x000A BACK-TO-FRONT ORDERING INDEX IN 2D DRAWING. (INT16)
      CDX_PROP_REGISTRYNUMBER = 0x000B # 0x000B A REGISTRY OR CATALOG NUMBER OF A MOLECULE OBJECT. (CDXSTRING)
      CDX_PROP_REGISTRYAUTHORITY = 0x000C # 0x000C A STRING THAT SPECIFIES THE AUTHORITY WHICH ISSUED A REGISTRY OR CATALOG NUMBER. SOME EXAMPLES OF REGISTRY AUTHORITIES ARE CAS BEILSTEIN ALDRICH AND MERCK. (CDXSTRING)
      CDX_PROP_UNUSED2 = 0x000D # 0x000D INDICATES THAT THIS OBJECT (THE REFERENCE OBJECT) IS AN ALIAS TO AN OBJECT ELSEWHERE IN THE DOCUMENT (THE TARGET OBJECT). THE ATTRIBUTES AND CONTAINED OBJECTS SHOULD BE TAKEN FROM THE TARGET OBJECT. (OBSOLETE)
      CDX_PROP_REPRESENTSPROPERTY = 0x000E # 0x000E INDICATES THAT THIS OBJECT REPRESENTS SOME PROPERTY IN SOME OTHER OBJECT. (CDXREPRESENTSPROPERTY)
      CDX_PROP_IGNOREWARNINGS = 0x000F # 0x000F SIGNIFIES WHETHER CHEMICAL WARNINGS SHOULD BE SUPPRESSED ON THIS OBJECT. (CDXBOOLEANIMPLIED)
      CDX_PROP_CHEMICALWARNING = 0x0010 # 0x0010 A WARNING CONCERNING POSSIBLE CHEMICAL PROBLEMS WITH THIS OBJECT. (CDXSTRING)
      CDX_PROP_VISIBLE = 0x0011 # 0x0011 THE OBJECT IS VISIBLE IF NON-ZERO. (CDXBOOLEAN)
      # CDX_PROP_SUPERSEDEDBY = 0x0012 # 0x0012 The ID of the object that should be read instead of this one.
      CDX_PROP_SUPERSEDEDBY = 0x0013 # 0x0013 The ID of the object that should be read instead of this one.

      # FONTS.
      CDX_PROP_FONTTABLE = 0x0100 # 0x0100 A LIST OF FONTS USED IN THE DOCUMENT. (CDXFONTTABLE)

      # COORDINATES.
      CDX_PROP_2DPOSITION = 0x0200 # 0x0200 THE 2D LOCATION (IN THE ORDER OF VERTICAL AND HORIZONTAL LOCATIONS) OF AN OBJECT. (CDXPOINT2D)
      CDX_PROP_3DPOSITION = 0x0201 # 0x0201 THE 3D LOCATION (IN THE ORDER OF X- Y- AND Z-LOCATIONS IN RIGHT-HANDED COORDINATE SYSTEM) OF AN OBJECT IN CDX COORDINATE UNITS. THE PRECISE MEANING OF THIS ATTRIBUTE VARIES DEPENDING ON THE TYPE OF OBJECT. (CDXPOINT3D)
      CDX_PROP_2DEXTENT = 0x0202 # 0x0202 THE WIDTH AND HEIGHT OF AN OBJECT IN CDX COORDINATE UNITS. THE PRECISE MEANING OF THIS ATTRIBUTE VARIES DEPENDING ON THE TYPE OF OBJECT. (CDXPOINT2D)
      CDX_PROP_3DEXTENT = 0x0203 # 0x0203 THE WIDTH HEIGHT AND DEPTH OF AN OBJECT IN CDX COORDINATE UNITS (RIGHT-HANDED COORDINATE SYSTEM). THE PRECISE MEANING OF THIS ATTRIBUTE VARIES DEPENDING ON THE TYPE OF OBJECT. (CDXPOINT3D)
      CDX_PROP_BOUNDINGBOX = 0x0204 # 0x0204 THE SMALLEST RECTANGLE THAT ENCLOSES THE GRAPHICAL REPRESENTATION OF THE OBJECT. (CDXRECTANGLE)
      CDX_PROP_ROTATIONANGLE = 0x0205 # 0x0205 THE ANGULAR ORIENTATION OF AN OBJECT IN DEGREES * 65536. (INT32)
      CDX_PROP_BOUNDSINPARENT = 0x0206 # 0x0206 THE BOUNDS OF THIS OBJECT IN THE COORDINATE SYSTEM OF ITS PARENT (USED FOR PAGES WITHIN TABLES). (CDXRECTANGLE)
      CDX_PROP_3DHEAD = 0x0207 # 0x0207 THE 3D LOCATION (IN THE ORDER OF X- Y- AND Z-LOCATIONS IN RIGHT-HANDED COORDINATE SYSTEM) OF THE HEAD OF AN OBJECT IN CDX COORDINATE UNITS. THE PRECISE MEANING OF THIS ATTRIBUTE VARIES DEPENDING ON THE TYPE OF OBJECT. (CDXPOINT3D)
      CDX_PROP_3DTAIL = 0x0208 # 0x0208 THE 3D LOCATION (IN THE ORDER OF X- Y- AND Z-LOCATIONS IN RIGHT-HANDED COORDINATE SYSTEM) OF THE TAIL OF AN OBJECT IN CDX COORDINATE UNITS. THE PRECISE MEANING OF THIS ATTRIBUTE VARIES DEPENDING ON THE TYPE OF OBJECT. (CDXPOINT3D)
      CDX_PROP_TOPLEFT = 0x0209 # 0x0209 THE LOCATION OF THE TOP-LEFT CORNER OF A QUADRILATERAL OBJECT POSSIBLY IN A ROTATED OR SKEWED FRAME. (CDXPOINT2D)
      CDX_PROP_TOPRIGHT = 0x020A # 0x020A THE LOCATION OF THE TOP-RIGHT CORNER OF A QUADRILATERAL OBJECT POSSIBLY IN A ROTATED OR SKEWED FRAME. (CDXPOINT2D)
      CDX_PROP_BOTTOMRIGHT = 0x020B # 0x020B THE LOCATION OF THE BOTTOM-RIGHT CORNER OF A QUADRILATERAL OBJECT POSSIBLY IN A ROTATED OR SKEWED FRAME. (CDXPOINT2D)
      CDX_PROP_BOTTOMLEFT = 0x020C # 0x020C THE LOCATION OF THE BOTTOM-LEFT CORNER OF A QUADRILATERAL OBJECT POSSIBLY IN A ROTATED OR SKEWED FRAME. (CDXPOINT2D)

      # COLORS.
      CDX_PROP_COLORTABLE = 0x0300 # 0x0300 THE COLOR PALETTE USED THROUGHOUT THE DOCUMENT. (CDXCOLORTABLE)
      CDX_PROP_FOREGROUNDCOLOR = 0x0301 # 0x0301 THE FOREGROUND COLOR OF AN OBJECT REPRESENTED AS THE TWO-BASED INDEX INTO THE OBJECT'S COLOR TABLE. (UINT16)
      CDX_PROP_BACKGROUNDCOLOR = 0x0302 # 0x0302 THE BACKGROUND COLOR OF AN OBJECT REPRESENTED AS THE TWO-BASED INDEX INTO THE OBJECT'S COLOR TABLE. (INT16)

      # ATOM PROPERTIES.
      CDX_PROP_NODE_TYPE = 0x0400 # 0x0400 THE TYPE OF A NODE OBJECT. (INT16)
      CDX_PROP_NODE_LABELDISPLAY = 0x0401 # 0x0401 THE CHARACTERISTICS OF NODE LABEL DISPLAY. (INT8)
      CDX_PROP_NODE_ELEMENT = 0x0402 # 0x0402 THE ATOMIC NUMBER OF THE ATOM REPRESENTING THIS NODE. (INT16)
      CDX_PROP_ATOM_ELEMENTLIST = 0x0403 # 0x0403 A LIST OF ATOMIC NUMBERS. (CDXELEMENTLIST)
      CDX_PROP_ATOM_FORMULA = 0x0404 # 0x0404 THE COMPOSITION OF A NODE REPRESENTING A FRAGMENT WHOSE COMPOSITION IS KNOWN BUT WHOSE CONNECTIVITY IS NOT. FOR EXAMPLE C<SUB>4</SUB>H<SUB>9</SUB> REPRESENTS A MIXTURE OF THE 4 BUTYL ISOMERS. (CDXFORMULA)
      CDX_PROP_ATOM_ISOTOPE = 0x0420 # 0x0420 THE ABSOLUTE ISOTOPIC MASS OF AN ATOM (2 FOR DEUTERIUM 14 FOR CARBON-14). (INT16)
      CDX_PROP_ATOM_CHARGE = 0x0421 # 0x0421 THE ATOMIC CHARGE OF AN ATOM. (INT8)
      CDX_PROP_ATOM_RADICAL = 0x0422 # 0x0422 THE ATOMIC RADICAL ATTRIBUTE OF AN ATOM. (UINT8)
      CDX_PROP_ATOM_RESTRICTFREESITES = 0x0423 # 0x0423 INDICATES THAT UP TO THE SPECIFIED NUMBER OF ADDITIONAL SUBSTITUENTS ARE PERMITTED ON THIS ATOM. (UINT8)
      CDX_PROP_ATOM_RESTRICTIMPLICITHYDROGENS = 0x0424 # 0x0424 SIGNIFIES THAT IMPLICIT HYDROGENS ARE NOT ALLOWED ON THIS ATOM. (CDXBOOLEANIMPLIED)
      CDX_PROP_ATOM_RESTRICTRINGBONDCOUNT = 0x0425 # 0x0425 THE NUMBER OF RING BONDS ATTACHED TO AN ATOM. (INT8)
      CDX_PROP_ATOM_RESTRICTUNSATURATEDBONDS = 0x0426 # 0x0426 INDICATES WHETHER UNSATURATION SHOULD BE PRESENT OR ABSENT. (INT8)
      CDX_PROP_ATOM_RESTRICTRXNCHANGE = 0x0427 # 0x0427 IF PRESENT SIGNIFIES THAT THE REACTION CHANGE OF AN ATOM MUST BE AS SPECIFIED. (CDXBOOLEANIMPLIED)
      CDX_PROP_ATOM_RESTRICTRXNSTEREO = 0x0428 # 0x0428 THE CHANGE OF STEREOCHEMISTRY OF AN ATOM DURING A REACTION. (INT8)
      CDX_PROP_ATOM_ABNORMALVALENCE = 0x0429 # 0x0429 SIGNIFIES THAT AN ABNORMAL VALENCE FOR AN ATOM IS PERMITTED. (CDXBOOLEANIMPLIED)
      CDX_PROP_UNUSED3 = 0x042A # 0x042A
      CDX_PROP_ATOM_NUMHYDROGENS = 0x042B # 0x042B THE NUMBER OF (EXPLICIT) HYDROGENS IN A LABELED ATOM CONSISTING OF ONE HEAVY ATOM AND (OPTIONALLY) THE SYMBOL H (E.G. CH<SUB>3</SUB>). (UINT16)
      CDX_PROP_UNUSED4 = 0x042C # 0x042C
      CDX_PROP_UNUSED5 = 0x042D # 0x042D
      CDX_PROP_ATOM_HDOT = 0x042E # 0x042E SIGNIFIES THE PRESENCE OF AN IMPLICIT HYDROGEN WITH STEREOCHEMISTRY SPECIFIED EQUIVALENT TO AN EXPLICIT H ATOM WITH A WEDGED BOND. (CDXBOOLEANIMPLIED)
      CDX_PROP_ATOM_HDASH = 0x042F # 0x042F SIGNIFIES THE PRESENCE OF AN IMPLICIT HYDROGEN WITH STEREOCHEMISTRY SPECIFIED EQUIVALENT TO AN EXPLICIT H ATOM WITH A HASHED BOND. (CDXBOOLEANIMPLIED)
      CDX_PROP_ATOM_GEOMETRY = 0x0430 # 0x0430 THE GEOMETRY OF THE BONDS ABOUT THIS ATOM. (INT8)
      CDX_PROP_ATOM_BONDORDERING = 0x0431 # 0x0431 AN ORDERING OF THE BONDS TO THIS NODE USED FOR STEREOCENTERS FRAGMENTS AND NAMED ALTERNATIVE GROUPS WITH MORE THAN ONE ATTACHMENT. (CDXOBJECTIDARRAY)
      CDX_PROP_NODE_ATTACHMENTS = 0x0432 # 0x0432 FOR MULTICENTER ATTACHMENT NODES OR VARIABLE ATTACHMENT NODES A LIST OF IDS OF THE NODES WHICH ARE MULTIPLY OR VARIABLY ATTACHED TO THIS NODE. (CDXOBJECTIDARRAYWITHCOUNTS)
      CDX_PROP_ATOM_GENERICNICKNAME = 0x0433 # 0x0433 THE NAME OF THE GENERIC NICKNAME. (CDXSTRING)
      CDX_PROP_ATOM_ALTGROUPID = 0x0434 # 0x0434 THE ID OF THE ALTERNATIVE GROUP OBJECT THAT DESCRIBES THIS NODE. (CDXOBJECTID)
      CDX_PROP_ATOM_RESTRICTSUBSTITUENTSUPTO = 0x0435 # 0x0435 INDICATES THAT SUBSTITUTION IS RESTRICTED TO NO MORE THAN THE SPECIFIED VALUE. (UINT8)
      CDX_PROP_ATOM_RESTRICTSUBSTITUENTSEXACTLY = 0x0436 # 0x0436 INDICATES THAT EXACTLY THE SPECIFIED NUMBER OF SUBSTITUENTS MUST BE PRESENT. (UINT8)
      CDX_PROP_ATOM_CIPSTEREOCHEMISTRY = 0x0437 # 0x0437 THE NODE'S ABSOLUTE STEREOCHEMISTRY ACCORDING TO THE CAHN-INGOLD-PRELOG SYSTEM. (INT8)
      CDX_PROP_ATOM_TRANSLATION = 0x0438 # 0x0438 PROVIDES FOR RESTRICTIONS ON WHETHER A GIVEN NODE MAY MATCH OTHER MORE- OR LESS-GENERAL NODES. (INT8)
      CDX_PROP_ATOM_ATOMNUMBER = 0x0439 # 0x0439 ATOM NUMBER AS TEXT. (CDXSTRING)
      CDX_PROP_ATOM_SHOWQUERY = 0x043A # 0x043A SHOW THE QUERY INDICATOR IF NON-ZERO. (CDXBOOLEAN)
      CDX_PROP_ATOM_SHOWSTEREO = 0x043B # 0x043B SHOW THE STEREOCHEMISTRY INDICATOR IF NON-ZERO. (CDXBOOLEAN)
      CDX_PROP_ATOM_SHOWATOMNUMBER = 0x043C # 0x043C SHOW THE ATOM NUMBER IF NON-ZERO. (CDXBOOLEAN)
      CDX_PROP_ATOM_LINKCOUNTLOW = 0x043D # 0x043D LOW END OF REPEAT COUNT FOR LINK NODES. (INT16)
      CDX_PROP_ATOM_LINKCOUNTHIGH = 0x043E # 0x043E HIGH END OF REPEAT COUNT FOR LINK NODES. (INT16)
      CDX_PROP_ATOM_ISOTOPICABUNDANCE = 0x043F # 0x043F ISOTOPIC ABUNDANCE OF THIS ATOM'S ISOTOPE. (INT8)
      CDX_PROP_ATOM_EXTERNALCONNECTIONTYPE = 0x0440 # 0x0440 TYPE OF EXTERNAL CONNECTION FOR ATOMS OF TYPE CDX_NODETYPE_EXTERNALCONNECTIONPOINT. (INT8)

      # MOLECULE PROPERTIES.
      CDX_PROP_MOLE_RACEMIC = 0x0500 # 0x0500 INDICATES THAT THE MOLECULE IS A RACEMIC MIXTURE. (CDXBOOLEAN)
      CDX_PROP_MOLE_ABSOLUTE = 0x0501 # 0x0501 INDICATES THAT THE MOLECULE HAS KNOWN ABSOLUTE CONFIGURATION. (CDXBOOLEAN)
      CDX_PROP_MOLE_RELATIVE = 0x0502 # 0x0502 INDICATES THAT THE MOLECULE HAS KNOWN RELATIVE STEREOCHEMISTRY BUT UNKNOWN ABSOLUTE CONFIGURATION. (CDXBOOLEAN)
      CDX_PROP_MOLE_FORMULA = 0x0503 # 0x0503 THE MOLECULAR FORMULA REPRESENTATION OF A MOLECULE OBJECT. (CDXFORMULA)
      CDX_PROP_MOLE_WEIGHT = 0x0504 # 0x0504 THE AVERAGE MOLECULAR WEIGHT OF A MOLECULE OBJECT. (FLOAT64)
      CDX_PROP_FRAG_CONNECTIONORDER = 0x0505 # 0x0505 AN ORDERED LIST OF ATTACHMENT POINTS WITHIN A FRAGMENT. (CDXOBJECTIDARRAY)

      # BOND PROPERTIES.
      CDX_PROP_BOND_ORDER = 0x0600 # 0x0600 THE ORDER OF A BOND OBJECT. (INT16)
      CDX_PROP_BOND_DISPLAY = 0x0601 # 0x0601 THE DISPLAY TYPE OF A BOND OBJECT. (INT16)
      CDX_PROP_BOND_DISPLAY2 = 0x0602 # 0x0602 THE DISPLAY TYPE FOR THE SECOND LINE OF A DOUBLE BOND. (INT16)
      CDX_PROP_BOND_DOUBLEPOSITION = 0x0603 # 0x0603 THE POSITION OF THE SECOND LINE OF A DOUBLE BOND. (INT16)
      CDX_PROP_BOND_BEGIN = 0x0604 # 0x0604 THE ID OF THE CDX NODE OBJECT AT THE FIRST END OF A BOND. (CDXOBJECTID)
      CDX_PROP_BOND_END = 0x0605 # 0x0605 THE ID OF THE CDX NODE OBJECT AT THE SECOND END OF A BOND. (CDXOBJECTID)
      CDX_PROP_BOND_RESTRICTTOPOLOGY = 0x0606 # 0x0606 INDICATES THE DESIRED TOPOLOGY OF A BOND IN A QUERY. (INT8)
      CDX_PROP_BOND_RESTRICTRXNPARTICIPATION = 0x0607 # 0x0607 SPECIFIES THAT A BOND IS AFFECTED BY A REACTION. (INT8)
      CDX_PROP_BOND_BEGINATTACH = 0x0608 # 0x0608 INDICATES WHERE WITHIN THE BOND_BEGIN NODE A BOND IS ATTACHED. (UINT8)
      CDX_PROP_BOND_ENDATTACH = 0x0609 # 0x0609 INDICATES WHERE WITHIN THE BOND_END NODE A BOND IS ATTACHED. (UINT8)
      CDX_PROP_BOND_CIPSTEREOCHEMISTRY = 0x060A # 0x060A THE BOND'S ABSOLUTE STEREOCHEMISTRY ACCORDING TO THE CAHN-INGOLD-PRELOG SYSTEM. (INT8)
      CDX_PROP_BOND_BONDORDERING = 0x060B # 0x060B ORDERED LIST OF ATTACHED BOND IDS. (CDXOBJECTIDARRAY)
      CDX_PROP_BOND_SHOWQUERY = 0x060C # 0x060C SHOW THE QUERY INDICATOR IF NON-ZERO. (CDXBOOLEAN)
      CDX_PROP_BOND_SHOWSTEREO = 0x060D # 0x060D SHOW THE STEREOCHEMISTRY INDICATOR IF NON-ZERO. (CDXBOOLEAN)
      CDX_PROP_BOND_CROSSINGBONDS = 0x060E # 0x060E UNORDERED LIST OF IDS OF BONDS THAT CROSS THIS ONE (EITHER ABOVE OR BELOW). (CDXOBJECTIDARRAY)
      CDX_PROP_BOND_SHOWRXN = 0x060F # 0x060F SHOW THE REACTION-CHANGE INDICATOR IF NON-ZERO. (CDXBOOLEAN)

      # TEXT PROPERTIES.
      CDX_PROP_TEXT = 0x0700 # 0x0700 THE TEXT OF A TEXT OBJECT. (CDXSTRING)
      CDX_PROP_JUSTIFICATION = 0x0701 # 0x0701 THE HORIZONTAL JUSTIFICATION OF A TEXT OBJECT. (INT8)
      CDX_PROP_LINEHEIGHT = 0x0702 # 0x0702 THE LINE HEIGHT OF A TEXT OBJECT. (UINT16)
      CDX_PROP_WORDWRAPWIDTH = 0x0703 # 0x0703 THE WORD-WRAP WIDTH OF A TEXT OBJECT. (INT16)
      CDX_PROP_LINESTARTS = 0x0704 # 0x0704 THE NUMBER OF LINES OF A TEXT OBJECT FOLLOWED BY THAT MANY VALUES INDICATING THE ZERO-BASED TEXT POSITION OF EACH LINE START. (INT16LISTWITHCOUNTS)
      CDX_PROP_LABELALIGNMENT = 0x0705 # 0x0705 THE ALIGNMENT OF THE TEXT WITH RESPECT TO THE NODE POSITION. (INT8)
      CDX_PROP_LABELLINEHEIGHT = 0x0706 # 0x0706 TEXT LINE HEIGHT FOR ATOM LABELS (INT16)
      CDX_PROP_CAPTIONLINEHEIGHT = 0x0707 # 0x0707 TEXT LINE HEIGHT FOR NON-ATOMLABEL TEXT OBJECTS (INT16)
      CDX_PROP_INTERPRETCHEMICALLY = 0x0708 # 0x0708 SIGNIFIES WHETHER TO THE TEXT LABEL SHOULD BE INTERPRETED CHEMICALLY (IF POSSIBLE). (CDXBOOLEANIMPLIED)

      # DOCUMENT PROPERTIES.
      CDX_PROP_MACPRINTINFO = 0x0800 # 0x0800 THE 120 BYTE MACINTOSH TPRINT DATA ASSOCIATED WITH THE CDX DOCUMENT OBJECT. REFER TO MACINTOSH TOOLBOX MANUAL FOR DETAILED DESCRIPTION. (UNFORMATTED)
      CDX_PROP_WINPRINTINFO = 0x0801 # 0x0801 THE WINDOWS DEVMODE STRUCTURE ASSOCIATED WITH THE CDX DOCUMENT OBJECT. (UNFORMATTED)
      CDX_PROP_PRINTMARGINS = 0x0802 # 0x0802 THE OUTER MARGINS OF THE DOCUMENT. (CDXRECTANGLE)
      CDX_PROP_CHAINANGLE = 0x0803 # 0x0803 THE DEFAULT CHAIN ANGLE SETTING IN DEGREES * 65536. (INT32)
      CDX_PROP_BONDSPACING = 0x0804 # 0x0804 THE SPACING BETWEEN SEGMENTS OF A MULTIPLE BOND MEASURED RELATIVE TO BOND LENGTH. (INT16)
      CDX_PROP_BONDLENGTH = 0x0805 # 0x0805 THE DEFAULT BOND LENGTH. (CDXCOORDINATE)
      CDX_PROP_BOLDWIDTH = 0x0806 # 0x0806 THE DEFAULT BOLD BOND WIDTH. (CDXCOORDINATE)
      CDX_PROP_LINEWIDTH = 0x0807 # 0x0807 THE DEFAULT LINE WIDTH. (CDXCOORDINATE)
      CDX_PROP_MARGINWIDTH = 0x0808 # 0x0808 THE DEFAULT AMOUNT OF SPACE SURROUNDING ATOM LABELS. (CDXCOORDINATE)
      CDX_PROP_HASHSPACING = 0x0809 # 0x0809 THE DEFAULT SPACING BETWEEN HASHED LINES USED IN WEDGED HASHED BONDS. (CDXCOORDINATE)
      CDX_PROP_LABELSTYLE = 0x080A # 0x080A THE DEFAULT STYLE FOR ATOM LABELS. (CDXFONTSTYLE)
      CDX_PROP_CAPTIONSTYLE = 0x080B # 0x080B THE DEFAULT STYLE FOR NON-ATOMLABEL TEXT OBJECTS. (CDXFONTSTYLE)
      CDX_PROP_CAPTIONJUSTIFICATION = 0x080C # 0x080C THE HORIZONTAL JUSTIFICATION OF A CAPTION (NON-ATOMLABEL TEXT OBJECT) (INT8)
      CDX_PROP_FRACTIONALWIDTHS = 0x080D # 0x080D SIGNIFIES WHETHER TO USE FRACTIONAL WIDTH INFORMATION WHEN DRAWING TEXT. (CDXBOOLEANIMPLIED)
      CDX_PROP_MAGNIFICATION = 0x080E # 0x080E THE VIEW MAGNIFICATION FACTOR (INT16)
      CDX_PROP_WIDTHPAGES = 0x080F # 0x080F THE WIDTH OF THE DOCUMENT IN PAGES. (INT16)
      CDX_PROP_HEIGHTPAGES = 0x0810 # 0x0810 THE HEIGHT OF THE DOCUMENT IN PAGES. (INT16)
      CDX_PROP_DRAWINGSPACETYPE = 0x0811 # 0x0811 THE TYPE OF DRAWING SPACE USED FOR THIS DOCUMENT. (INT8)
      CDX_PROP_WIDTH = 0x0812 # 0x0812 THE WIDTH OF AN OBJECT IN CDX COORDINATE UNITS POSSIBLY IN A ROTATED OR SKEWED FRAME. (CDXCOORDINATE)
      CDX_PROP_HEIGHT = 0x0813 # 0x0813 THE HEIGHT OF AN OBJECT IN CDX COORDINATE UNITS POSSIBLY IN A ROTATED OR SKEWED FRAME. (CDXCOORDINATE)
      CDX_PROP_PAGEOVERLAP = 0x0814 # 0x0814 THE AMOUNT OF OVERLAP OF PAGES WHEN A POSTER IS TILED. (CDXCOORDINATE)
      CDX_PROP_HEADER = 0x0815 # 0x0815 THE TEXT OF THE HEADER. (CDXSTRING)
      CDX_PROP_HEADERPOSITION = 0x0816 # 0x0816 THE VERTICAL OFFSET OF THE HEADER BASELINE FROM THE TOP OF THE PAGE. (CDXCOORDINATE)
      CDX_PROP_FOOTER = 0x0817 # 0x0817 THE TEXT OF THE FOOTER. (CDXSTRING)
      CDX_PROP_FOOTERPOSITION = 0x0818 # 0x0818 THE VERTICAL OFFSET OF THE FOOTER BASELINE FROM THE BOTTOM OF THE PAGE. (CDXCOORDINATE)
      CDX_PROP_PRINTTRIMMARKS = 0x0819 # 0x0819 IF PRESENT TRIM MARKS ARE TO PRINTED IN THE MARGINS. (CDXBOOLEANIMPLIED)
      CDX_PROP_LABELSTYLEFONT = 0x081A # 0x081A THE DEFAULT FONT FAMILY FOR ATOM LABELS. (INT16)
      CDX_PROP_CAPTIONSTYLEFONT = 0x081B # 0x081B THE DEFAULT FONT STYLE FOR CAPTIONS (NON-ATOM-LABEL TEXT OBJECTS). (INT16)
      CDX_PROP_LABELSTYLESIZE = 0x081C # 0x081C THE DEFAULT FONT SIZE FOR ATOM LABELS. (INT16)
      CDX_PROP_CAPTIONSTYLESIZE = 0x081D # 0x081D THE DEFAULT FONT SIZE FOR CAPTIONS (NON-ATOM-LABEL TEXT OBJECTS). (INT16)
      CDX_PROP_LABELSTYLEFACE = 0x081E # 0x081E THE DEFAULT FONT STYLE FOR ATOM LABELS. (INT16)
      CDX_PROP_CAPTIONSTYLEFACE = 0x081F # 0x081F THE DEFAULT FONT FACE FOR CAPTIONS (NON-ATOM-LABEL TEXT OBJECTS). (INT16)
      CDX_PROP_LABELSTYLECOLOR = 0x0820 # 0x0820 THE DEFAULT COLOR FOR ATOM LABELS (INT16)
      CDX_PROP_CAPTIONSTYLECOLOR = 0x0821 # 0x0821 THE DEFAULT COLOR FOR CAPTIONS (NON-ATOM-LABEL TEXT OBJECTS). (INT16)
      CDX_PROP_BONDSPACINGABS = 0x0822 # 0x0822 THE ABSOLUTE DISTANCE BETWEEN SEGMENTS OF A MULTIPLE BOND. (CDXCOORDINATE)
      CDX_PROP_LABELJUSTIFICATION = 0x0823 # 0x0823 THE DEFAULT JUSTIFICATION FOR ATOM LABELS. (INT8)
      CDX_PROP_FIXINPLACEEXTENT = 0x0824 # 0x0824 DEFINES A SIZE FOR OLE IN-PLACE EDITING. (CDXPOINT2D)
      CDX_PROP_SIDE = 0x0825 # 0x0825 A SPECIFIC SIDE OF AN OBJECT (RECTANGLE). (INT16)
      CDX_PROP_FIXINPLACEGAP = 0x0826 # 0x0826 DEFINES A PADDING FOR OLE IN-PLACE EDITING. (CDXPOINT2D)

      # WINDOW PROPERTIES.
      CDX_PROP_WINDOW_ISZOOMED = 0x0900 # 0x0900 SIGNIFIES WHETHER THE MAIN VIEWING WINDOW IS ZOOMED (MAXIMIZED). (CDXBOOLEANIMPLIED)
      CDX_PROP_WINDOW_POSITION = 0x0901 # 0x0901 THE TOP-LEFT POSITION OF THE MAIN VIEWING WINDOW. (CDXPOINT2D)
      CDX_PROP_WINDOW_SIZE = 0x0902 # 0x0902 HEIGHT AND WIDTH OF THE DOCUMENT WINDOW. (CDXPOINT2D)

      # GRAPHIC OBJECT PROPERTIES.
      CDX_PROP_GRAPHIC_TYPE = 0x0A00 # 0x0A00 THE TYPE OF GRAPHICAL OBJECT. (INT16)
      CDX_PROP_LINE_TYPE = 0x0A01 # 0x0A01 THE TYPE OF A LINE OBJECT. (INT16)
      CDX_PROP_ARROW_TYPE = 0x0A02 # 0x0A02 THE TYPE OF ARROW OBJECT WHICH REPRESENTS LINE ARROW ARC RECTANGLE OR ORBITAL. (INT16)
      CDX_PROP_RECTANGLE_TYPE = 0x0A03 # 0x0A03 THE TYPE OF A RECTANGLE OBJECT. (INT16)
      CDX_PROP_OVAL_TYPE = 0x0A04 # 0x0A04 THE TYPE OF AN ARROW OBJECT THAT REPRESENTS A CIRCLE OR ELLIPSE. (INT16)
      CDX_PROP_ORBITAL_TYPE = 0x0A05 # 0x0A05 THE TYPE OF ORBITAL OBJECT. (INT16)
      CDX_PROP_BRACKET_TYPE = 0x0A06 # 0x0A06 THE TYPE OF SYMBOL OBJECT. (INT16)
      CDX_PROP_SYMBOL_TYPE = 0x0A07 # 0x0A07 THE TYPE OF SYMBOL OBJECT. (INT16)
      CDX_PROP_CURVE_TYPE = 0x0A08 # 0x0A08 THE TYPE OF CURVE OBJECT. (INT16)
      CDX_PROP_ARROW_HEADSIZE = 0x0A20 # 0x0A20 THE SIZE OF THE ARROW'S HEAD. (INT16)
      CDX_PROP_ARC_ANGULARSIZE = 0x0A21 # 0x0A21 THE SIZE OF AN ARC (IN DEGREES * 10 SO 90 DEGREES = 900). (INT16)
      CDX_PROP_BRACKET_LIPSIZE = 0x0A22 # 0x0A22 THE SIZE OF A BRACKET. (INT16)
      CDX_PROP_CURVE_POINTS = 0x0A23 # 0x0A23 THE B&EACUTE;ZIER CURVE'S CONTROL POINT LOCATIONS. (CDXCURVEPOINTS)
      CDX_PROP_BRACKET_USAGE = 0x0A24 # 0x0A24 THE SYNTACTICAL CHEMICAL MEANING OF THE BRACKET (SRU MER MON XLINK ETC). (INT8)
      CDX_PROP_POLYMER_REPEATPATTERN = 0x0A25 # 0x0A25 THE HEAD-TO-TAIL CONNECTIVITY OF OBJECTS CONTAINED WITHIN THE BRACKET. (INT8)
      CDX_PROP_POLYMER_FLIPTYPE = 0x0A26 # 0x0A26 THE FLIP STATE OF OBJECTS CONTAINED WITHIN THE BRACKET. (INT8)
      CDX_PROP_BRACKETEDOBJECTS = 0x0A27 # 0x0A27 THE SET OF OBJECTS CONTAINED IN A BRACKETEDGROUP. (CDXOBJECTIDARRAY)
      CDX_PROP_BRACKET_REPEATCOUNT = 0x0A28 # 0x0A28 THE NUMBER OF TIMES A MULTIPLE-GROUP BRACKETEDGROUP IS REPEATED. (INT16)
      CDX_PROP_BRACKET_COMPONENTORDER = 0x0A29 # 0x0A29 THE COMPONENT ORDER ASSOCIATED WITH A BRACKETEDGROUP. (INT16)
      CDX_PROP_BRACKET_SRULABEL = 0x0A2A # 0x0A2A THE LABEL ASSOCIATED WITH A BRACKETEDGROUP THAT REPRESENTS AN SRU. (CDXSTRING)
      CDX_PROP_BRACKET_GRAPHICID = 0x0A2B # 0x0A2B THE ID OF A GRAPHICAL OBJECT (BRACKET BRACE OR PARENTHESIS) ASSOCIATED WITH A BRACKET ATTACHMENT. (CDXOBJECTID)
      CDX_PROP_BRACKET_BONDID = 0x0A2C # 0x0A2C THE ID OF A BOND THAT CROSSES A BRACKET ATTACHMENT. (CDXOBJECTID)
      CDX_PROP_BRACKET_INNERATOMID = 0x0A2D # 0x0A2D THE ID OF THE NODE LOCATED WITHIN THE BRACKETED GROUP AND ATTACHED TO A BOND THAT CROSSES A BRACKET ATTACHMENT. (CDXOBJECTID)
      CDX_PROP_CURVE_POINTS3D = 0x0A2E # 0x0A2E THE B&EACUTE;ZIER CURVE'S CONTROL POINT LOCATIONS. (CDXCURVEPOINTS3D)

      # EMBEDDED PICTURES.
      CDX_PROP_PICTURE_EDITION = 0x0A60 # 0x0A60 THE SECTION INFORMATION (SECTIONHANDLE) OF THE MACINTOSH PUBLISH & SUBSCRIBE EDITION EMBEDDED IN THE CDX PICTURE OBJECT. (UNFORMATTED)
      CDX_PROP_PICTURE_EDITIONALIAS = 0x0A61 # 0x0A61 THE ALIAS INFORMATION OF THE MACINTOSH PUBLISH & SUBSCRIBE EDITION EMBEDDED IN THE CDX PICTURE OBJECT. (UNFORMATTED)
      CDX_PROP_MACPICT = 0x0A62 # 0x0A62 A MACINTOSH PICT DATA OBJECT. (UNFORMATTED)
      CDX_PROP_WINDOWSMETAFILE = 0x0A63 # 0x0A63 A MICROSOFT WINDOWS METAFILE OBJECT. (UNFORMATTED)
      CDX_PROP_OLEOBJECT = 0x0A64 # 0x0A64 AN OLE OBJECT. (UNFORMATTED)
      CDX_PROP_ENHANCEDMETAFILE = 0x0A65 # 0x0A65 A MICROSOFT WINDOWS ENHANCED METAFILE OBJECT. (UNFORMATTED)

      # Spectrum Properties
      CDX_PROP_SPECTRUM_XSPACING = 0x0A80 # 0x0A80 THE SPACING IN LOGICAL UNITS (PPM HZ WAVENUMBERS) BETWEEN POINTS ALONG THE X-AXIS OF AN EVENLY-SPACED GRID. (FLOAT64)
      CDX_PROP_SPECTRUM_XLOW = 0x0A81 # 0x0A81 THE FIRST DATA POINT FOR THE X-AXIS OF AN EVENLY-SPACED GRID. (FLOAT64)
      CDX_PROP_SPECTRUM_XTYPE = 0x0A82 # 0x0A82 THE TYPE OF UNITS THE X-AXIS REPRESENTS. (INT16)
      CDX_PROP_SPECTRUM_YTYPE = 0x0A83 # 0x0A83 THE TYPE OF UNITS THE Y-AXIS REPRESENTS. (INT16)
      CDX_PROP_SPECTRUM_XAXISLABEL = 0x0A84 # 0x0A84 A LABEL FOR THE X-AXIS. (CDXSTRING)
      CDX_PROP_SPECTRUM_YAXISLABEL = 0x0A85 # 0x0A85 A LABEL FOR THE Y-AXIS. (CDXSTRING)
      CDX_PROP_SPECTRUM_DATAPOINT = 0x0A86 # 0x0A86 THE Y-AXIS VALUES FOR THE SPECTRUM. IT IS AN ARRAY OF DOUBLE VALUES CORRESPONDING TO X-AXIS VALUES. (FLOAT64)
      CDX_PROP_SPECTRUM_CLASS = 0x0A87 # 0x0A87 THE TYPE OF SPECTRUM REPRESENTED. (INT16)
      CDX_PROP_SPECTRUM_YLOW = 0x0A88 # 0x0A88 Y VALUE TO BE USED TO OFFSET DATA WHEN STORING XML. (FLOAT64)
      CDX_PROP_SPECTRUM_YSCALE = 0x0A89 # 0x0A89 Y SCALING USED TO SCALE DATA WHEN STORING XML. (FLOAT64)

      # TLC PROPERTIES
      CDX_PROP_TLC_ORIGINFRACTION = 0x0AA0 # 0x0AA0 THE DISTANCE OF THE ORIGIN LINE FROM THE BOTTOM OF A TLC PLATE AS A FRACTION OF THE TOTAL HEIGHT OF THE PLATE. (FLOAT64)
      CDX_PROP_TLC_SOLVENTFRONTFRACTION = 0x0AA1 # 0x0AA1 THE DISTANCE OF THE SOLVENT FRONT FROM THE TOP OF A TLC PLATE AS A FRACTION OF THE TOTAL HEIGHT OF THE PLATE. (FLOAT64)
      CDX_PROP_TLC_SHOWORIGIN = 0x0AA2 # 0x0AA2 SHOW THE ORIGIN LINE NEAR THE BASE OF THE TLC PLATE IF NON-ZERO. (CDXBOOLEAN)
      CDX_PROP_TLC_SHOWSOLVENTFRONT = 0x0AA3 # 0x0AA3 SHOW THE SOLVENT FRONT LINE NEAR THE TOP OF THE TLC PLATE IF NON-ZERO. (CDXBOOLEAN)
      CDX_PROP_TLC_SHOWBORDERS = 0x0AA4 # 0x0AA4 SHOW BORDERS AROUND THE EDGES OF THE TLC PLATE IF NON-ZERO. (CDXBOOLEAN)
      CDX_PROP_TLC_SHOWSIDETICKS = 0x0AA5 # 0x0AA5 SHOW TICKMARKS UP THE SIDE OF THE TLC PLATE IF NON-ZERO. (CDXBOOLEAN)
      CDX_PROP_TLC_RF = 0x0AB0 # 0x0AB0 THE RETENTION FACTOR OF AN INDIVIDUAL SPOT. (FLOAT64)
      CDX_PROP_TLC_TAIL = 0x0AB1 # 0x0AB1 THE LENGTH OF THE "TAIL" OF AN INDIVIDUAL SPOT. (CDXCOORDINATE)
      CDX_PROP_TLC_SHOWRF = 0x0AB2 # 0x0AB2 SHOW THE SPOT'S RETENTION FRACTION (RF) VALUE IF NON-ZERO. (CDXBOOLEAN)

      # ALTERNATE GROUP PROPERTIES
      CDX_PROP_NAMEDALTERNATIVEGROUP_TEXTFRAME = 0x0B00 # 0x0B00 THE BOUNDING BOX OF UPPER PORTION OF THE NAMED ALTERNATIVE GROUP CONTAINING THE NAME OF THE GROUP. (CDXRECTANGLE)
      CDX_PROP_NAMEDALTERNATIVEGROUP_GROUPFRAME = 0x0B01 # 0x0B01 THE BOUNDING BOX OF THE LOWER PORTION OF THE NAMED ALTERNATIVE GROUP CONTAINING THE DEFINITION OF THE GROUP. (CDXRECTANGLE)
      CDX_PROP_NAMEDALTERNATIVEGROUP_VALENCE = 0x0B02 # 0x0B02 THE NUMBER OF ATTACHMENT POINTS IN EACH ALTERNATIVE IN A NAMED ALTERNATIVE GROUP. (INT16)

      # GEOMETRY AND CONSTRAINT PROPERTIES
      CDX_PROP_GEOMETRICFEATURE = 0x0B80 # 0x0B80 THE TYPE OF THE GEOMETRICAL FEATURE (POINT LINE PLANE ETC.). (INT8)
      CDX_PROP_RELATIONVALUE = 0x0B81 # 0x0B81 THE NUMERIC RELATIONSHIP (IF ANY) AMONG THE BASIS OBJECTS USED TO DEFINE THIS OBJECT. (INT8)
      CDX_PROP_BASISOBJECTS = 0x0B82 # 0x0B82 AN ORDERED LIST OF OBJECTS USED TO DEFINE THIS OBJECT. (CDXOBJECTIDARRAY)
      CDX_PROP_CONSTRAINTTYPE = 0x0B83 # 0x0B83 THE CONSTRAINT TYPE (DISTANCE OR ANGLE). (INT8)
      CDX_PROP_CONSTRAINTMIN = 0x0B84 # 0x0B84 THE MINIMUM VALUE OF THE CONSTRAINT (FLOAT64)
      CDX_PROP_CONSTRAINTMAX = 0x0B85 # 0x0B85 THE MAXIMUM VALUE OF THE CONSTRAINT (FLOAT64)
      CDX_PROP_IGNOREUNCONNECTEDATOMS = 0x0B86 # 0x0B86 SIGNIFIES WHETHER UNCONNECTED ATOMS SHOULD BE IGNORED WITHIN THE EXCLUSION SPHERE. (CDXBOOLEANIMPLIED)
      CDX_PROP_DIHEDRALISCHIRAL = 0x0B87 # 0x0B87 SIGNIFIES WHETHER A DIHEDRAL IS SIGNED OR UNSIGNED. (CDXBOOLEANIMPLIED)
      CDX_PROP_POINTISDIRECTED = 0x0B88 # 0x0B88 FOR A POINT BASED ON A NORMAL SIGNIFIES WHETHER IT IS IN A SPECIFIC DIRECTION RELATIVE TO THE REFERENCE POINT. (CDXBOOLEANIMPLIED)

      # REACTION PROPERTIES
      CDX_PROP_REACTIONSTEP_ATOM_MAP = 0x0C00 # 0x0C00 REPRESENTS PAIRS OF MAPPED ATOM IDS; EACH PAIR IS A REACTANT ATOM MAPPED TO TO A PRODUCT ATOM. (CDXOBJECTIDARRAY)
      CDX_PROP_REACTIONSTEP_REACTANTS = 0x0C01 # 0x0C01 AN ORDER LIST OF REACTANTS PRESENT IN THE REACTION STEP. (CDXOBJECTIDARRAY)
      CDX_PROP_REACTIONSTEP_PRODUCTS = 0x0C02 # 0x0C02 AN ORDER LIST OF PRODUCTS PRESENT IN THE REACTION STEP. (CDXOBJECTIDARRAY)
      CDX_PROP_REACTIONSTEP_PLUSSES = 0x0C03 # 0x0C03 AN ORDERED LIST OF PLUSES USED TO SEPARATE COMPONENTS OF THE REACTION STEP. (CDXOBJECTIDARRAY)
      CDX_PROP_REACTIONSTEP_ARROWS = 0x0C04 # 0x0C04 AN ORDERED LIST OF ARROWS USED TO SEPARATE COMPONENTS OF THE REACTION STEP. (CDXOBJECTIDARRAY)
      CDX_PROP_REACTIONSTEP_OBJECTSABOVEARROW = 0x0C05 # 0x0C05 AN ORDER LIST OF OBJECTS ABOVE THE ARROW IN THE REACTION STEP. (CDXOBJECTIDARRAY)
      CDX_PROP_REACTIONSTEP_OBJECTSBELOWARROW = 0x0C06 # 0x0C06 AN ORDER LIST OF OBJECTS BELOW THE ARROW IN THE REACTION STEP. (CDXOBJECTIDARRAY)
      CDX_PROP_REACTIONSTEP_ATOM_MAP_MANUAL = 0x0C07 # 0x0C07 REPRESENTS PAIRS OF MAPPED ATOM IDS; EACH PAIR IS A REACTANT ATOM MAPPED TO TO A PRODUCT ATOM. (CDXOBJECTIDARRAY)
      CDX_PROP_REACTIONSTEP_ATOM_MAP_AUTO = 0x0C08 # 0x0C08 REPRESENTS PAIRS OF MAPPED ATOM IDS; EACH PAIR IS A REACTANT ATOM MAPPED TO TO A PRODUCT ATOM. (CDXOBJECTIDARRAY)

      # CDOBJECTTAG PROPERTIES
      CDX_PROP_OBJECTTAG_TYPE = 0x0D00 # 0x0D00 THE TAG'S DATA TYPE. (INT16)
      CDX_PROP_UNUSED6 = 0x0D01 # 0x0D01 OBSOLETE (OBSOLETE)
      CDX_PROP_UNUSED7 = 0x0D02 # 0x0D02 OBSOLETE (OBSOLETE)
      CDX_PROP_OBJECTTAG_TRACKING = 0x0D03 # 0x0D03 THE TAG WILL PARTICIPATE IN TRACKING IF NON-ZERO. (CDXBOOLEAN)
      CDX_PROP_OBJECTTAG_PERSISTENT = 0x0D04 # 0x0D04 THE TAG WILL BE RESAVED TO A CDX FILE IF NON-ZERO. (CDXBOOLEAN)
      CDX_PROP_OBJECTTAG_VALUE = 0x0D05 # 0x0D05 THE VALUE IS A INT32 FLOAT64 OR UNFORMATTED STRING DEPENDING ON THE VALUE OF OBJECTTAG_TYPE. (VARIES)
      CDX_PROP_POSITIONING = 0x0D06 # 0x0D06 HOW THE INDICATOR SHOULD BE POSITIONED WITH RESPECT TO ITS CONTAINING OBJECT. (INT8)
      CDX_PROP_POSITIONINGANGLE = 0x0D07 # 0x0D07 ANGULAR POSITIONING IN RADIANS * 65536. (INT32)
      CDX_PROP_POSITIONINGOFFSET = 0x0D08 # 0x0D08 OFFSET POSITIONING. (CDXPOINT2D)

      # CDSEQUENCE PROPERTIES
      CDX_PROP_SEQUENCE_IDENTIFIER = 0x0E00 # 0x0E00 A UNIQUE (BUT OTHERWISE RANDOM) IDENTIFIER FOR A GIVEN SEQUENCE OBJECT. (CDXSTRING)

      # CDCROSSREFERENCE PROPERTIES
      CDX_PROP_CROSSREFERENCE_CONTAINER = 0x0F00 # 0x0F00 AN EXTERNAL OBJECT CONTAINING (AS AN EMBEDDED OBJECT) THE DOCUMENT CONTAINING THE SEQUENCE OBJECT BEING REFERENCED. (CDXSTRING)
      CDX_PROP_CROSSREFERENCE_DOCUMENT = 0x0F01 # 0x0F01 AN EXTERNAL DOCUMENT CONTAINING THE SEQUENCE OBJECT BEING REFERENCED. (CDXSTRING)
      CDX_PROP_CROSSREFERENCE_IDENTIFIER = 0x0F02 # 0x0F02 A UNIQUE (BUT OTHERWISE RANDOM) IDENTIFIER FOR A GIVEN CROSS-REFERENCE OBJECT. (CDXSTRING)
      CDX_PROP_CROSSREFERENCE_SEQUENCE = 0x0F03 # 0x0F03 A VALUE MATCHING THE SEQUENCEIDENTIFIER OF THE SEQUENCE OBJECT TO BE REFERENCED. (CDXSTRING)

      # MISCELLANEOUS PROPERTIES.
      CDX_PROP_TEMPLATE_PANEHEIGHT = 0x1000 # 0x1000 THE HEIGHT OF THE VIEWING WINDOW OF A TEMPLATE GRID. (CDXCOORDINATE)
      CDX_PROP_TEMPLATE_NUMROWS = 0x1001 # 0x1001 THE NUMBER OF ROWS OF THE CDX TEMPLATEGRID OBJECT. (INT16)
      CDX_PROP_TEMPLATE_NUMCOLUMNS = 0x1002 # 0x1002 THE NUMBER OF COLUMNS OF THE CDX TEMPLATEGRID OBJECT. (INT16)

      CDX_PROP_GROUP_INTEGRAL = 0x1100 # 0x1100 THE GROUP IS CONSIDERED TO BE INTEGRAL (NON-SUBDIVISIBLE) IF NON-ZERO. (CDXBOOLEAN)

      CDX_PROP_SPLITTERPOSITIONS = 0x1FF0 # 0x1FF0 AN ARRAY OF VERTICAL POSITIONS THAT SUBDIVIDE A PAGE INTO REGIONS. (CDXOBJECTIDARRAY)
      CDX_PROP_PAGEDEFINITION = 0x1FF1 # 0x1FF1 AN ARRAY OF VERTICAL POSITIONS THAT SUBDIVIDE A PAGE INTO REGIONS. (CDXOBJECTIDARRAY)

      # USER DEFINED PROPERTIES
      # FIRST 1024 TAGS ARE RESERVED FOR TEMPORARY TAGS USED ONLY DURING THE RUNTIME.
      CDX_USER_TEMPORARYBEGIN = CDX_TAG_USER_DEFINED
      CDX_USER_TEMPORARYEND = CDX_TAG_USER_DEFINED + 0x0400

      # OBJECTS.
      CDX_OBJ_DOCUMENT = CDX_TAG_OBJECT # 0x8000
      CDX_OBJ_PAGE = 0x8001 # 0x8001
      CDX_OBJ_GROUP = 0x8002 # 0x8002
      CDX_OBJ_FRAGMENT = 0x8003 # 0x8003
      CDX_OBJ_NODE = 0x8004 # 0x8004
      CDX_OBJ_BOND = 0x8005 # 0x8005
      CDX_OBJ_TEXT = 0x8006 # 0x8006
      CDX_OBJ_GRAPHIC = 0x8007 # 0x8007
      CDX_OBJ_CURVE = 0x8008 # 0x8008
      CDX_OBJ_EMBEDDEDOBJECT = 0x8009 # 0x8009
      CDX_OBJ_NAMEDALTERNATIVEGROUP = 0x800A # 0x800A
      CDX_OBJ_TEMPLATEGRID = 0x800B # 0x800B
      CDX_OBJ_REGISTRYNUMBER = 0x800C # 0x800C
      CDX_OBJ_REACTIONSCHEME = 0x800D # 0x800D
      CDX_OBJ_REACTIONSTEP = 0x800E # 0x800E
      CDX_OBJ_OBJECTDEFINITION = 0x800F # 0x800F
      CDX_OBJ_SPECTRUM = 0x8010 # 0x8010
      CDX_OBJ_OBJECTTAG = 0x8011 # 0x8011
      CDX_OBJ_OLECLIENTITEM = 0x8012 # 0x8012 # OBSOLETE
      CDX_OBJ_SEQUENCE = 0x8013 # 0x8013
      CDX_OBJ_CROSSREFERENCE = 0x8014 # 0x8014
      CDX_OBJ_SPLITTER = 0x8015 # 0x8015
      CDX_OBJ_TABLE = 0x8016 # 0x8016
      CDX_OBJ_BRACKETEDGROUP = 0x8017 # 0x8017
      CDX_OBJ_BRACKETATTACHMENT = 0x8018 # 0x8018
      CDX_OBJ_CROSSINGBOND = 0x8019 # 0x8019
      CDX_OBJ_BORDER = 0x8020 # 0x8020
      CDX_OBJ_GEOMETRY = 0x8021 # 0x8021
      CDX_OBJ_CONSTRAINT = 0x8022 # 0x8022
      CDX_OBJ_TLCPLATE = 0x8023 # 0x8023
      CDX_OBJ_TLCLANE = 0x8024 # 0x8024
      CDX_OBJ_TLCSPOT = 0x8025 # 0x8025
      CDX_OBJ_CHEMICALPROPERTY = 0x8026
      CDX_OBJ_ARROW = 0x8027
      # ADD NEW OBJECTS HERE
      CDX_OBJ_UNKNOWNOBJECT = 0x8FFF

      # CDX_NODETYPE_UNSPECIFIED
      # CDX_NODETYPE_ELEMENT
      # CDX_NODETYPE_ELEMENTLIST
      # CDX_NODETYPE_ELEMENTLISTNICKNAME
      # CDX_NODETYPE_NICKNAME
      # CDX_NODETYPE_FRAGMENT
      # CDX_NODETYPE_FORMULA
      # CDX_NODETYPE_GENERICNICKNAME
      # CDX_NODETYPE_ANONYMOUSALTERNATIVEGROUP
      # CDX_NODETYPE_NAMEDALTERNATIVEGROUP
      # CDX_NODETYPE_MULTIATTACHMENT
      # CDX_NODETYPE_VARIABLEATTACHMENT
      # CDX_NODETYPE_EXTERNALCONNECTIONPOINT
      # CDX_NODETYPE_LINKNODE

      # CDX_LABELDISPLAY_AUTO
      # CDX_LABELDISPLAY_LEFT
      # CDX_LABELDISPLAY_CENTER
      # CDX_LABELDISPLAY_RIGHT
      # CDX_LABELDISPLAY_ABOVE
      # CDX_LABELDISPLAY_BELOW
      # CDX_LABELDISPLAY_BESTINITIAL

      CDX_RADICAL_NONE = 0
      CDX_RADICAL_SINGLET = 1 # DIRADICAL SINGLET  (TWO DOTS)
      CDX_RADICAL_DOUBLET = 2 # MONORADICAL      (ONE DOT)
      CDX_RADICAL_TRIPLET = 3 # DIRADICAL TRIPLET  (TWO DOTS)

      CDX_ISOTOPE_NATURAL = 0

      CDX_RINGBONDCOUNT_UNSPECIFIED = -1
      CDX_RINGBONDCOUNT_NORINGBONDS = 0
      CDX_RINGBONDCOUNT_ASDRAWN = 1
      CDX_RINGBONDCOUNT_SIMPLERING = 2
      CDX_RINGBONDCOUNT_FUSION = 3
      CDX_RINGBONDCOUNT_SPIROORHIGHER = 4

      CDX_UNSATURATION_UNSPECIFIED = 0
      CDX_UNSATURATION_MUSTBEABSENT = 1
      CDX_UNSATURATION_MUSTBEPRESENT = 2
      # CDX_UNSATURATIONLASTENUM

      CDX_REACTIONSTEREO_UNSPECIFIED = 0
      CDX_REACTIONSTEREO_INVERSION = 1
      CDX_REACTIONSTEREO_RETENTION = 2

      CDX_TRANSLATION_EQUAL = 0
      CDX_TRANSLATION_BROAD = 1
      CDX_TRANSLATION_NARROW = 2
      CDX_TRANSLATION_ANY = 3

      CDX_ABUNDANCE_UNSPECIFIED = 0
      CDX_ABUNDANCE_ANY = 1
      CDX_ABUNDANCE_NATURAL = 2
      CDX_ABUNDANCE_ENRICHED = 3
      CDX_ABUNDANCE_DEFICIENT = 4
      CDX_ABUNDANCE_NONNATURAL = 5

      CDX_EXTERNALCONNECTION_UNSPECIFIED = 0
      CDX_EXTERNALCONNECTION_DIAMOND = 1
      CDX_EXTERNALCONNECTION_STAR = 2
      CDX_EXTERNALCONNECTION_POLYMERBEAD = 3
      CDX_EXTERNALCONNECTION_WAVY = 4

      CDX_ATOMGEOMETRY_UNKNOWN = 0
      CDX_ATOMGEOMETRY_1LIGAND = 1
      CDX_ATOMGEOMETRY_LINEAR = 2
      CDX_ATOMGEOMETRY_BENT = 3
      CDX_ATOMGEOMETRY_TRIGONALPLANAR = 4
      CDX_ATOMGEOMETRY_TRIGONALPYRAMIDAL = 5
      CDX_ATOMGEOMETRY_SQUAREPLANAR = 6
      CDX_ATOMGEOMETRY_TETRAHEDRAL = 7
      CDX_ATOMGEOMETRY_TRIGONALBIPYRAMIDAL = 8
      CDX_ATOMGEOMETRY_SQUAREPYRAMIDAL = 9
      CDX_ATOMGEOMETRY_5LIGAND = 10
      CDX_ATOMGEOMETRY_OCTAHEDRAL = 11
      CDX_ATOMGEOMETRY_6LIGAND = 12
      CDX_ATOMGEOMETRY_7LIGAND = 13
      CDX_ATOMGEOMETRY_8LIGAND = 14
      CDX_ATOMGEOMETRY_9LIGAND = 15
      CDX_ATOMGEOMETRY_10LIGAND = 16

      CDX_BONDORDER_SINGLE = 0x0001
      CDX_BONDORDER_DOUBLE = 0x0002
      CDX_BONDORDER_TRIPLE = 0x0004
      CDX_BONDORDER_QUADRUPLE = 0x0008
      CDX_BONDORDER_QUINTUPLE = 0x0010
      CDX_BONDORDER_SEXTUPLE = 0x0020
      CDX_BONDORDER_HALF = 0x0040
      CDX_BONDORDER_ONEHALF = 0x0080
      CDX_BONDORDER_TWOHALF = 0x0100
      CDX_BONDORDER_THREEHALF = 0x0200
      CDX_BONDORDER_FOURHALF = 0x0400
      CDX_BONDORDER_FIVEHALF = 0x0800
      CDX_BONDORDER_DATIVE = 0x1000
      CDX_BONDORDER_IONIC = 0x2000
      CDX_BONDORDER_HYDROGEN = 0x4000
      CDX_BONDORDER_THREECENTER = 0x8000
      CDX_BONDORDER_SINGLEORDOUBLE = CDX_BONDORDER_SINGLE | CDX_BONDORDER_DOUBLE
      CDX_BONDORDER_SINGLEORAROMATIC = CDX_BONDORDER_SINGLE | CDX_BONDORDER_ONEHALF
      CDX_BONDORDER_DOUBLEORAROMATIC = CDX_BONDORDER_DOUBLE | CDX_BONDORDER_ONEHALF
      CDX_BONDORDER_ANY = -1

      CDX_BONDDISPLAY_SOLID = 0
      CDX_BONDDISPLAY_DASH = 1
      CDX_BONDDISPLAY_HASH = 2
      CDX_BONDDISPLAY_WEDGEDHASHBEGIN = 3
      CDX_BONDDISPLAY_WEDGEDHASHEND = 4
      CDX_BONDDISPLAY_BOLD = 5
      CDX_BONDDISPLAY_WEDGEBEGIN = 6
      CDX_BONDDISPLAY_WEDGEEND = 7
      CDX_BONDDISPLAY_WAVY = 8
      CDX_BONDDISPLAY_HOLLOWWEDGEBEGIN = 9
      CDX_BONDDISPLAY_HOLLOWWEDGEEND = 10
      CDX_BONDDISPLAY_WAVYWEDGEBEGIN = 11
      CDX_BONDDISPLAY_WAVYWEDGEEND = 12
      CDX_BONDDISPLAY_DOT = 13
      CDX_BONDDISPLAY_DASHDOT = 14

      CDX_BONDDOUBLEPOSITION_AUTOCENTER = 0x0000
      CDX_BONDDOUBLEPOSITION_AUTORIGHT = 0x0001
      CDX_BONDDOUBLEPOSITION_AUTOLEFT = 0x0002
      CDX_BONDDOUBLEPOSITION_USERCENTER = 0x0100
      CDX_BONDDOUBLEPOSITION_USERRIGHT = 0x0101
      CDX_BONDDOUBLEPOSITION_USERLEFT = 0x0102

      CDX_BONDTOPOLOGY_UNSPECIFIED = 0
      CDX_BONDTOPOLOGY_RING = 1
      CDX_BONDTOPOLOGY_CHAIN = 2
      CDX_BONDTOPOLOGY_RINGORCHAIN = 3

      CDX_BONDREACTIONPARTICIPATION_UNSPECIFIED = 0
      CDX_BONDREACTIONPARTICIPATION_REACTIONCENTER = 1
      CDX_BONDREACTIONPARTICIPATION_MAKEORBREAK = 2
      CDX_BONDREACTIONPARTICIPATION_CHANGETYPE = 3
      CDX_BONDREACTIONPARTICIPATION_MAKEANDCHANGE = 4
      CDX_BONDREACTIONPARTICIPATION_NOTREACTIONCENTER = 5
      CDX_BONDREACTIONPARTICIPATION_NOCHANGE = 6
      CDX_BONDREACTIONPARTICIPATION_UNMAPPED = 7

      CDX_TEXTJUSTIFICATION_RIGHT = -1
      # CDX_TEXTJUSTIFICATION_LEFT
      # CDX_TEXTJUSTIFICATION_CENTER
      # CDX_TEXTJUSTIFICATION_FULL
      # CDX_TEXTJUSTIFICATION_ABOVE
      # CDX_TEXTJUSTIFICATION_BELOW
      # CDX_TEXTJUSTIFICATION_AUTO
      # CDX_TEXTJUSTIFICATION_BESTINITIAL

      # CDX_TAG_TYPE_UNKNOWN     "UNKNOWN"
      # CDX_TAG_TYPE_QUERY     "QUERY"
      # CDX_TAG_TYPE_RXN       "REACTION"
      # CDX_TAG_TYPE_STEREO      "STEREO"
      # CDX_TAG_TYPE_NUMBER      "NUMBER"
      # CDX_TAG_TYPE_HEADING     "HEADING"
      # CDX_TAG_TYPE_IDTERM      "IDTERM"
      # CDX_TAG_TYPE_BRACKETUSAGE  "BRACKETUSAGE"
      # CDX_TAG_TYPE_POLYMERREPEAT "POLYMERREPEAT"
      # CDX_TAG_TYPE_POLYMERFLIP   "POLYMERFLIP"
      # CDX_TAG_TYPE_DEVIATION   "DEVIATION"
      # CDX_TAG_TYPE_DISTANCE    "DISTANCE"
      # CDX_TAG_TYPE_ANGLE     "ANGLE"
      # CDX_TAG_TYPE_RF        "RF"

      # CDX_POSITIONINGTYPE_AUTO = 0
      # CDX_POSITIONINGTYPE_ANGLE
      # CDX_POSITIONINGTYPE_OFFSET
      # CDX_POSITIONINGTYPE_ABSOLUTE

      # CDX_PAGEDEFINITION_UNDEFINED = 0
      # CDX_PAGEDEFINITION_CENTER
      # CDX_PAGEDEFINITION_TL4
      # CDX_PAGEDEFINITION_IDTERM
      # CDX_PAGEDEFINITION_FLUSHLEFT
      # CDX_PAGEDEFINITION_FLUSHRIGHT
      # CDX_PAGEDEFINITION_REACTION1
      # CDX_PAGEDEFINITION_REACTION2
      # CDX_PAGEDEFINITION_MULTICOLUMNTL4
      # CDX_PAGEDEFINITION_MULTICOLUMNNONTL4
      # CDX_PAGEDEFINITION_USERDEFINED

      CDX_LINEHEIGHT_VARIABLE = 0
      CDX_LINEHEIGHT_AUTOMATIC = 1

      # CDX_GRAPHICTYPE_UNDEFINED = 0
      # CDX_GRAPHICTYPE_LINE
      # CDX_GRAPHICTYPE_ARC
      # CDX_GRAPHICTYPE_RECTANGLE
      # CDX_GRAPHICTYPE_OVAL
      # CDX_GRAPHICTYPE_ORBITAL
      # CDX_GRAPHICTYPE_BRACKET
      # CDX_GRAPHICTYPE_SYMBOL

      # CDX_BRACKETTYPE_ROUNDPAIR
      # CDX_BRACKETTYPE_SQUAREPAIR
      # CDX_BRACKETTYPE_CURLYPAIR
      # CDX_BRACKETTYPE_SQUARE
      # CDX_BRACKETTYPE_CURLY
      # CDX_BRACKETTYPE_ROUND

      CDX_RECTANGLETYPE_PLAIN = 0x0000
      CDX_RECTANGLETYPE_ROUNDEDGE = 0x0001
      CDX_RECTANGLETYPE_SHADOW = 0x0002
      CDX_RECTANGLETYPE_SHADED = 0x0004
      CDX_RECTANGLETYPE_FILLED = 0x0008
      CDX_RECTANGLETYPE_DASHED = 0x0010
      CDX_RECTANGLETYPE_BOLD = 0x0020

      CDX_OVALTYPE_CIRCLE = 0x0001
      CDX_OVALTYPE_SHADED = 0x0002
      CDX_OVALTYPE_FILLED = 0x0004
      CDX_OVALTYPE_DASHED = 0x0008
      CDX_OVALTYPE_BOLD = 0x0010
      CDX_OVALTYPE_SHADOWED = 0x0020

      # CDX_SYMBOLTYPE_LONEPAIR
      # CDX_SYMBOLTYPE_ELECTRON
      # CDX_SYMBOLTYPE_RADICALCATION
      # CDX_SYMBOLTYPE_RADICALANION
      # CDX_SYMBOLTYPE_CIRCLEPLUS
      # CDX_SYMBOLTYPE_CIRCLEMINUS
      # CDX_SYMBOLTYPE_DAGGER
      # CDX_SYMBOLTYPE_DOUBLEDAGGER
      # CDX_SYMBOLTYPE_PLUS
      # CDX_SYMBOLTYPE_MINUS
      # CDX_SYMBOLTYPE_RACEMIC
      # CDX_SYMBOLTYPE_ABSOLUTE
      # CDX_SYMBOLTYPE_RELATIVE

      CDX_LINETYPE_SOLID = 0x0000
      CDX_LINETYPE_DASHED = 0x0001
      CDX_LINETYPE_BOLD = 0x0002
      CDX_LINETYPE_WAVY = 0x0004

      CDX_ARROWTYPE_NOHEAD = 0
      CDX_ARROWTYPE_HALFHEAD = 1
      CDX_ARROWTYPE_FULLHEAD = 2
      CDX_ARROWTYPE_RESONANCE = 4
      CDX_ARROWTYPE_EQUILIBRIUM = 8
      CDX_ARROWTYPE_HOLLOW = 16
      CDX_ARROWTYPE_RETROSYNTHETIC = 32

      # CDX_ORBITALTYPE_S         # S ORBITAL
      # CDX_ORBITALTYPE_OVAL        # OVAL-SHAPED SIGMA OR PI ORBITAL
      # CDX_ORBITALTYPE_LOBE        # ONE LOBE OF A P ORBITAL
      # CDX_ORBITALTYPE_P         # COMPLETE P ORBITAL
      # CDX_ORBITALTYPE_HYBRIDPLUS      # HYDRID ORBITAL
      # CDX_ORBITALTYPE_HYBRIDMINUS   # HYDRID ORBITAL (OPPOSITE SHADING)
      # CDX_ORBITALTYPE_DZ2PLUS     # DZ2 ORBITAL
      # CDX_ORBITALTYPE_DZ2MINUS      # DZ2 ORBITAL (OPPOSITE SHADING)
      # CDX_ORBITALTYPE_DXY       # DXY ORBITAL

      # CDX_ORBITALTYPE_SSHADED = 0x0100  # SHADED S ORBITAL
      # CDX_ORBITALTYPE_OVALSHADED      # SHADED OVAL-SHAPED SIGMA OR PI ORBITAL
      # CDX_ORBITALTYPE_LOBESHADED      # SHADED SINGLE LOBE OF A P ORBITAL
      # CDX_ORBITALTYPE_PSHADED     # SHADED COMPLETE P ORBITAL

      # CDX_ORBITALTYPE_SFILLED = 0x0200  # FILLED S ORBITAL
      # CDX_ORBITALTYPE_OVALFILLED      # FILLED OVAL-SHAPED SIGMA OR PI ORBITAL
      # CDX_ORBITALTYPE_LOBEFILLED      # FILLED SINGLE LOBE OF A P ORBITAL
      # CDX_ORBITALTYPE_PFILLED     # FILLED COMPLETE P ORBITAL
      # CDX_ORBITALTYPE_HYBRIDPLUSFILLED  # FILLED HYDRID ORBITAL
      # CDX_ORBITALTYPE_HYBRIDMINUSFILLED # FILLED HYDRID ORBITAL (OPPOSITE SHADING)
      # CDX_ORBITALTYPE_DZ2PLUSFILLED   # FILLED DZ2 ORBITAL
      # CDX_ORBITALTYPE_DZ2MINUSFILLED    # FILLED DZ2 ORBITAL (OPPOSITE SHADING)
      # CDX_ORBITALTYPE_DXYFILLED     # FILLED DXY ORBITAL

      CDX_BRACKETUSAGE_UNSPECIFIED = 0
      CDX_BRACKETUSAGE_ANYPOLYMER = 18
      CDX_BRACKETUSAGE_COMPONENT = 13
      CDX_BRACKETUSAGE_COPOLYMER = 6
      CDX_BRACKETUSAGE_COPOLYMERALTERNATING = 7
      CDX_BRACKETUSAGE_COPOLYMERBLOCK = 9
      CDX_BRACKETUSAGE_COPOLYMERRANDOM = 8
      CDX_BRACKETUSAGE_CROSSLINK = 10
      CDX_BRACKETUSAGE_GENERIC = 17
      CDX_BRACKETUSAGE_GRAFT = 11
      CDX_BRACKETUSAGE_MER = 5
      CDX_BRACKETUSAGE_MIXTUREORDERED = 15
      CDX_BRACKETUSAGE_MIXTUREUNORDERED = 14
      CDX_BRACKETUSAGE_MODIFICATION = 12
      CDX_BRACKETUSAGE_MONOMER = 4
      CDX_BRACKETUSAGE_MULTIPLEGROUP = 16
      CDX_BRACKETUSAGE_SRU = 3
      CDX_BRACKETUSAGE_UNUSED1 = 1
      CDX_BRACKETUSAGE_UNUSED2 = 2

      # CDX_POLYMERREPEATPATTERN_HEADTOTAIL = 0
      # CDX_POLYMERREPEATPATTERN_HEADTOHEAD
      # CDX_POLYMERREPEATPATTERN_EITHERUNKNOWN

      # CDX_POLYMERFLIPTYPE_UNSPECIFIED = 0
      # CDX_POLYMERFLIPTYPE_NOFLIP
      # CDX_POLYMERFLIPTYPE_FLIP

      # CDX_SPECTRUMYTYPE_UNKNOWN
      # CDX_SPECTRUMYTYPE_ABSORBANCE
      # CDX_SPECTRUMYTYPE_TRANSMITTANCE
      # CDX_SPECTRUMYTYPE_PERCENTTRANSMITTANCE
      # CDX_SPECTRUMYTYPE_OTHER
      # CDX_SPECTRUMYTYPE_ARBITRARYUNITS

      # CDX_SPECTRUMXTYPE_UNKNOWN
      # CDX_SPECTRUMXTYPE_WAVENUMBERS
      # CDX_SPECTRUMXTYPE_MICRONS
      # CDX_SPECTRUMXTYPE_HERTZ
      # CDX_SPECTRUMXTYPE_MASSUNITS
      # CDX_SPECTRUMXTYPE_PARTSPERMILLION
      # CDX_SPECTRUMXTYPE_OTHER

      # CDX_SPECTRUMCLASS_UNKNOWN
      # CDX_SPECTRUMCLASS_CHROMATOGRAM
      # CDX_SPECTRUMCLASS_INFRARED
      # CDX_SPECTRUMCLASS_UVVIS
      # CDX_SPECTRUMCLASS_XRAYDIFFRACTION
      # CDX_SPECTRUMCLASS_MASSSPECTRUM
      # CDX_SPECTRUMCLASS_NMR
      # CDX_SPECTRUMCLASS_RAMAN
      # CDX_SPECTRUMCLASS_FLUORESCENCE
      # CDX_SPECTRUMCLASS_ATOMIC

      # CDX_DRAWINGSPACE_PAGES
      # CDX_DRAWINGSPACE_POSTER

      # CDX_CIPATOM_UNDETERMINED = 0
      # CDX_CIPATOM_NONE
      # CDX_CIPATOM_R
      # CDX_CIPATOM_S
      # CDX_CIPATOM_R
      # CDX_CIPATOM_S
      # CDX_CIPATOM_UNSPECIFIED           # NO HASH/WEDGE BUT IF THERE WERE ONE IT WOULD HAVE STEREOCHEMISTRY.

      # CDX_CIPBOND_UNDETERMINED = 0
      # CDX_CIPBOND_NONE
      # CDX_CIPBOND_E
      # CDX_CIPBOND_Z

      # CDX_OBJECTTAGTYPE_UNDEFINED = 0
      # CDX_OBJECTTAGTYPE_DOUBLE
      # CDX_OBJECTTAGTYPE_LONG
      # CDX_OBJECTTAGTYPE_STRING

      # CDX_SIDETYPE_UNDEFINED = 0
      # CDX_SIDETYPE_TOP
      # CDX_SIDETYPE_LEFT
      # CDX_SIDETYPE_BOTTOM
      # CDX_SIDETYPE_RIGHT

      # CDX_GEOMETRICFEATURE_UNDEFINED = 0
      # CDX_GEOMETRICFEATURE_POINTFROMPOINTPOINTDISTANCE
      # CDX_GEOMETRICFEATURE_POINTFROMPOINTPOINTPERCENTAGE
      # CDX_GEOMETRICFEATURE_POINTFROMPOINTNORMALDISTANCE
      # CDX_GEOMETRICFEATURE_LINEFROMPOINTS
      # CDX_GEOMETRICFEATURE_PLANEFROMPOINTS
      # CDX_GEOMETRICFEATURE_PLANEFROMPOINTLINE
      # CDX_GEOMETRICFEATURE_CENTROIDFROMPOINTS
      # CDX_GEOMETRICFEATURE_NORMALFROMPOINTPLANE

      # CDX_CONSTRAINTTYPE_UNDEFINED = 0
      # CDX_CONSTRAINTTYPE_DISTANCE
      # CDX_CONSTRAINTTYPE_ANGLE
      # CDX_CONSTRAINTTYPE_EXCLUSIONSPHERE

      CDX_CHARSETUNKNOWN = 0
      CDX_CHARSETEBCDICOEM = 37
      CDX_CHARSETMSDOSUS = 437
      CDX_CHARSETEBCDIC500V1 = 500
      CDX_CHARSETARABICASMO708 = 708
      # CDX_CHARSETARABICASMO449P
      # CDX_CHARSETARABICTRANSPARENT
      CDX_CHARSETARABICTRANSPARENTASMO = 720
      CDX_CHARSETGREEK437G = 737
      CDX_CHARSETBALTICOEM = 775
      CDX_CHARSETMSDOSLATIN1 = 850
      CDX_CHARSETMSDOSLATIN2 = 852
      CDX_CHARSETIBMCYRILLIC = 855
      CDX_CHARSETIBMTURKISH = 857
      CDX_CHARSETMSDOSPORTUGUESE = 860
      # CDX_CHARSETMSDOSICELANDIC
      # CDX_CHARSETHEBREWOEM
      # CDX_CHARSETMSDOSCANADIANFRENCH
      # CDX_CHARSETARABICOEM
      # CDX_CHARSETMSDOSNORDIC
      # CDX_CHARSETMSDOSRUSSIAN
      CDX_CHARSETIBMMODERNGREEK = 869
      CDX_CHARSETTHAI = 874
      # CDX_CHARSETEBCDIC
      CDX_CHARSETJAPANESE = 932
      CDX_CHARSETCHINESESIMPLIFIED = 936 # PRC SINGAPORE
      CDX_CHARSETKOREAN = 949
      CDX_CHARSETCHINESETRADITIONAL = 950 # TAIWAN HONG KONG
      CDX_CHARSETUNICODEISO10646 = 1200
      CDX_CHARSETWIN31EASTERNEUROPEAN = 1250
      # CDX_CHARSETWIN31CYRILLIC
      # CDX_CHARSETWIN31LATIN1
      # CDX_CHARSETWIN31GREEK
      # CDX_CHARSETWIN31TURKISH
      # CDX_CHARSETHEBREW
      # CDX_CHARSETARABIC
      # CDX_CHARSETBALTIC
      # CDX_CHARSETVIETNAMESE
      CDX_CHARSETKOREANJOHAB = 1361
      CDX_CHARSETMACROMAN = 10000
      # CDX_CHARSETMACJAPANESE
      # CDX_CHARSETMACTRADCHINESE
      # CDX_CHARSETMACKOREAN
      # CDX_CHARSETMACARABIC
      # CDX_CHARSETMACHEBREW
      # CDX_CHARSETMACGREEK
      # CDX_CHARSETMACCYRILLIC
      # CDX_CHARSETMACRESERVED
      # CDX_CHARSETMACDEVANAGARI
      # CDX_CHARSETMACGURMUKHI
      # CDX_CHARSETMACGUJARATI
      # CDX_CHARSETMACORIYA
      # CDX_CHARSETMACBENGALI
      # CDX_CHARSETMACTAMIL
      # CDX_CHARSETMACTELUGU
      # CDX_CHARSETMACKANNADA
      # CDX_CHARSETMACMALAYALAM
      # CDX_CHARSETMACSINHALESE
      # CDX_CHARSETMACBURMESE
      # CDX_CHARSETMACKHMER
      # CDX_CHARSETMACTHAI
      # CDX_CHARSETMACLAO
      # CDX_CHARSETMACGEORGIAN
      # CDX_CHARSETMACARMENIAN
      # CDX_CHARSETMACSIMPCHINESE
      # CDX_CHARSETMACTIBETAN
      # CDX_CHARSETMACMONGOLIAN
      # CDX_CHARSETMACETHIOPIC
      # CDX_CHARSETMACCENTRALEUROROMAN
      # CDX_CHARSETMACVIETNAMESE
      # CDX_CHARSETMACEXTARABIC
      # CDX_CHARSETMACUNINTERPRETED
      CDX_CHARSETMACICELANDIC = 10079
      CDX_CHARSETMACTURKISH = 10081
    end
  end
end
