x-common-volumes:
  - &vhome homedir:/home/chemotion-dev
  - &vapp ..:/home/chemotion-dev/app


services:
  app:
    build:
      context: '.'
      dockerfile: 'Dockerfile.chemotion-dev'
      # args:
        # source_image: ${DOCKER_DEV_IMAGE:-ubuntu:jammy}  # Build ARG for base image
        # FULL_BUILD: ${FULL_BUILD:-false}
    image: ""
    volumes:
      - *vhome
      - *vapp
  webpacker:
    build:
      context: '.'
      dockerfile: 'Dockerfile.chemotion-dev'
      # args:
        # source_image: ${DOCKER_DEV_IMAGE:-ubuntu:jammy}  # Build ARG for base image
        # FULL_BUILD: ${FULL_BUILD:-false}
    image: ""
    volumes:
      - *vhome
      - *vapp
