export const SET_CDD_INSTANCE = 'SET_CDD_INSTANCE';
export const SCAN_FILE_FOR_MOLECULES = 'SCAN_FILE_FOR_MOLECULES';
export const SCAN_FILE_FOR_REACTIONS = 'SCAN_FILE_FOR_REACTIONS';

export const HIDE_FILE = 'HIDE_FILE';
export const HIDE_SCHEME = 'HIDE_SCHEME';
export const HIDE_MOLECULE = 'HIDE_MOLECULE';
export const HIDE_REACTION = 'HIDE_REACTION';

export const APPROVE_FILE = 'APPROVE_FILE';
export const APPROVE_SCHEME = 'APPROVE_SCHEME';

export const EDIT_MOLECULE_COMMENT = 'EDIT_MOLECULE_COMMENT';
export const EDIT_REACTION_COMMENT = 'EDIT_REACTION_COMMENT';

export const SELECT_MOLECULE = 'SELECT_MOLECULE';
export const SELECT_REACTION = 'SELECT_REACTION';

export const CLEAN_UP = 'CLEAN_UP';
export const CLEAN_UP_REQUEST_SVG = 'CLEAN_UP_REQUEST_SVG';

export const CHANGE_VIEW = 'CHANGE_VIEW';
export const VIEW_SCANNED_FILES = 'VIEW_SCANNED_FILES';
export const VIEW_ABBREVIATION = 'VIEW_ABBREVIATION';
export const VIEW_FILE_STORAGE = 'VIEW_FILE_STORAGE';
export const VIEW_ARCHIVED_MANAGEMENT = 'VIEW_ARCHIVED_MANAGEMENT';

export const UPDATE_REAGENTS_SMILES = 'UPDATE_REAGENTS_SMILES';

export const GET_CURRENT_VERSION = 'GET_CURRENT_VERSION';

export const SET_LOADING = 'SET_LOADING';
export const UNSET_LOADING = 'UNSET_LOADING';
export const SET_IMPORT = 'SET_IMPORT';
export const UNSET_IMPORT = 'UNSET_IMPORT';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const RESET_NOTIFICATION = 'RESET_NOTIFICATION';

export const RETRIEVE_STORED_FILES = 'RETRIEVE_STORED_FILES';
export const GET_FILE_RESULTS = 'GET_FILE_RESULTS';
export const GET_SCANNED_OUTPUT = 'GET_SCANNED_OUTPUT';
export const RESCAN_STORED_FILE = 'RESCAN_STORED_FILE';
export const DELETE_STORED_FILE = 'DELETE_STORED_FILE';
export const DOWNLOAD_STORED_FILE = 'DOWNLOAD_STORED_FILE';
export const MARK_CORRECT = 'MARK_CORRECT';
export const UPLOAD_TO_STORE = 'UPLOAD_TO_STORE';

export const GET_SCHEME_PREVIEW = 'GET_SCHEME_PREVIEW';
export const SAVE_PNG = 'SAVE_PNG';

export const UPDATE_METADATA = 'UPDATE_METADATA';
export const IMPORT_DATA = 'IMPORT_DATA';
export const UPDATE_ITEM_FIELD = 'UPDATE_ITEM_FIELD';

export const TOGGLE_ALIAS_POLYMER = 'TOGGLE_ALIAS_POLYMER';

export const SET_EDITING_MOLECULE_ID = 'SET_EDITING_MOLECULE_ID';

export const FETCH_SVG = 'FETCH_SVG';

export const TOGGLE_FILE_EXPAND = 'TOGGLE_FILE_EXPAND';
export const TOGGLE_SCHEME_EXPAND = 'TOGGLE_SCHEME_EXPAND';

export const SET_ARCHIVED_VALUE = 'SET_ARCHIVED_VALUE';

export const DEFAULT = 'DEFAULT';
