class BackfillElementTagCollectionLabels < ActiveRecord::Migration[6.1]
  # Bring element_tags.collection_labels into the post-refactor shape in one set-based pass.
  #
  # The collection-share refactor changed collection_tag's format to `{ id }` only but shipped no
  # data migration, so pre-refactor tags carry stale collection_labels: extra fields, `null`
  # entries (which crash the client), and synchronized-collection entries keyed by the now-dropped
  # sync_collections_users.id (which the client misresolves to an unrelated collection).
  #
  # This rewrites each collection_labels array to distinct `{ id: <collection_id> }`, keeping only
  # real collection entries. The old format always kept one is_synchronized=false entry per
  # collection with id = collection.id, so dropping null and is_synchronized=true entries leaves
  # exactly the real collection ids. RefreshElementTagJob (cron) re-derives authoritatively over
  # time; this migration makes the data correct immediately and is idempotent.
  def up
    # Rewrite collection_labels for every taggable except Molecule (handled below).
    execute(<<~SQL)
      UPDATE element_tags e
      SET taggable_data = jsonb_set(
            e.taggable_data,
            '{collection_labels}',
            COALESCE(cleaned.arr, '[]'::jsonb)
          )
      FROM (
        SELECT et.id,
               jsonb_agg(DISTINCT jsonb_build_object('id', (x->>'id')::int)) FILTER (
                 WHERE jsonb_typeof(x) = 'object'
                   AND (x->>'id') IS NOT NULL
                   AND COALESCE(x->>'is_synchronized', 'false') <> 'true'
               ) AS arr
        FROM element_tags et
        CROSS JOIN LATERAL jsonb_array_elements(et.taggable_data->'collection_labels') x
        WHERE et.taggable_type <> 'Molecule'
          AND et.taggable_data ? 'collection_labels'
          AND jsonb_typeof(et.taggable_data->'collection_labels') = 'array'
        GROUP BY et.id
      ) cleaned
      WHERE e.id = cleaned.id;
    SQL

    # Molecules never belong to collections (collection_tag is nil for them): drop the key.
    execute(<<~SQL)
      UPDATE element_tags
      SET taggable_data = taggable_data - 'collection_labels'
      WHERE taggable_type = 'Molecule' AND taggable_data ? 'collection_labels';
    SQL
  end

  def down
    # collection_labels is derived data, regenerated by RefreshElementTagJob; nothing to revert.
  end
end
