class BackfillElementTagCollectionLabels < ActiveRecord::Migration[6.1]
  # Authoritative, set-based rebuild of element_tags.collection_labels straight from the collection
  # join tables — the same source of truth as Taggable#collection_tag, which emits one
  # { id: <collection.id> } per non-deleted collection the element belongs to, excluding the locked
  # "All". Reconstructing from the join row (rather than cleaning the pre-refactor array in place)
  # is what makes shared collections correct: after the collection-share refactor a shared
  # collection is a real collection the element is still joined to via collections_<element>, so the
  # join yields its real id with no dependency on the old format's redundant is_synchronized=false
  # entry and no leftover sync_collections_users.id entries.
  #
  # Replaces the model path (RefreshElementTagJob full regenerate measured ~108 min collection-only
  # / ~24 h full over ~514k tags) with SQL that never instantiates a model: a few seconds over the
  # same data. Idempotent — overwrites whatever stale shape was present (legacy fields, null
  # entries, dropped sync ids, or a missing shared-collection entry) with the live join-derived set.

  # taggable_type => [join table, element FK]. Vessel is intentionally absent: vessels.id is uuid
  # but element_tags.taggable_id is integer, so vessels never carry element_tags (and the join would
  # be a type error). Molecule is handled separately (it is never in a collection).
  TAGGABLES = [
    ['Sample',                           'collections_samples',                              'sample_id'],
    ['Reaction',                         'collections_reactions',                            'reaction_id'],
    ['Wellplate',                        'collections_wellplates',                           'wellplate_id'],
    ['Screen',                           'collections_screens',                              'screen_id'],
    ['ResearchPlan',                     'collections_research_plans',                       'research_plan_id'],
    ['CelllineSample',                   'collections_celllines',                            'cellline_sample_id'],
    ['DeviceDescription',                'collections_device_descriptions',                  'device_description_id'],
    ['SequenceBasedMacromoleculeSample', 'collections_sequence_based_macromolecule_samples', 'sequence_based_macromolecule_sample_id'],
    ['Labimotion::Element',              'collections_elements',                             'element_id'],
  ].freeze

  def up
    TAGGABLES.each do |type, join_table, fk|
      # 1) Rebuild collection_labels for tags whose element is in >= 1 qualifying collection.
      execute(<<~SQL)
        UPDATE element_tags e
        SET taggable_data = jsonb_set(
              COALESCE(e.taggable_data, '{}'::jsonb), '{collection_labels}', d.arr)
        FROM (
          SELECT et.id,
                 jsonb_agg(DISTINCT jsonb_build_object('id', cj.collection_id)) AS arr
          FROM element_tags et
          JOIN #{join_table} cj ON cj.#{fk} = et.taggable_id AND cj.deleted_at IS NULL
          JOIN collections c     ON c.id = cj.collection_id AND c.deleted_at IS NULL
          WHERE et.taggable_type = #{quote(type)}
            AND NOT (c.label = 'All' AND c.is_locked)
          GROUP BY et.id
        ) d
        WHERE e.id = d.id;
      SQL

      # 2) Drop the key for tags of this type with NO qualifying collection — Taggable
      #    compact_blank!s an empty collection_labels away, so an absent key is the correct shape.
      execute(<<~SQL)
        UPDATE element_tags e
        SET taggable_data = e.taggable_data - 'collection_labels'
        WHERE e.taggable_type = #{quote(type)}
          AND e.taggable_data ? 'collection_labels'
          AND NOT EXISTS (
            SELECT 1 FROM #{join_table} cj
            JOIN collections c ON c.id = cj.collection_id AND c.deleted_at IS NULL
            WHERE cj.#{fk} = e.taggable_id AND cj.deleted_at IS NULL
              AND NOT (c.label = 'All' AND c.is_locked)
          );
      SQL
    end

    # Molecules never belong to collections (collection_tag is nil for them): drop the key.
    execute(<<~SQL)
      UPDATE element_tags
      SET taggable_data = taggable_data - 'collection_labels'
      WHERE taggable_type = 'Molecule' AND taggable_data ? 'collection_labels';
    SQL
  end

  def down
    # collection_labels is derived data, regenerated by RefreshElementTagJob; nothing to revert.
  end
end
